### ISSUE TITLE
Mediawiker stopped working

### ISSUE THREAD

**Issue by dbobak** [tosher/Mediawiker#102]
I'm using Sublime Text v. 3, build 3125 on Windows 10 Pro.
I've just noticed, that mediawiker stopped working. The Mediawiker menu in tools is grayed out, there is no mediawiker command in command palette.

I've uninstalled mediawiker completely, removed my custom configuration files and installed it again, but still no success.

**Comment by dbobak** [comment]
This is the log from the ST console:
```
DPI scale: 1
startup, version: 3125 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/deni/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/deni/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/deni/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["LaTeXTools", "Markdown", "sublemacspro", "Vintage"]
pre session restore time: 0.392097
loading dictionary Packages/Dictionaries/Polish.dic
startup time: 0.632097
first paint time: 0.633097
first paint time: 0.634097
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-tabulate
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-oauthlib
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.51-requests-oauthlib
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Boxy Theme.BT
reloading plugin Bracketeer.bracketeer
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.changes
reloading plugin BracketHighlighter.support
reloading plugin Chain of Command.chain
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin Context.base
reloading plugin Context.called_method
reloading plugin Context.class
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "class in C:\Users\deni\AppData\Roaming\Sublime Text 3\Installed Packages\Context.sublime-package", line 6, in <module>
ImportError: No module named 'IndentationNavigation'
reloading plugin Context.clipboard
reloading plugin Context.context
reloading plugin Context.filename
reloading plugin Context.nesting
reloading plugin Context.selection
reloading plugin Context.settings
reloading plugin Context.statement
reloading plugin Context.text
reloading plugin Dictionaries.Dictionaries
reloading plugin Expression.commands
reloading plugin Expression.expression
reloading plugin Expression.listeners
reloading plugin FileList.commands
reloading plugin FileList.file_list
reloading plugin FindKeyConflicts.find_key_conflicts
reloading plugin FolderFiles.commands
reloading plugin FolderFiles.folder_files
reloading plugin Google Spell Check.google-spell-check
reloading plugin Keymaps.Keymaps
reloading plugin knitr.chunksend
reloading plugin LaTeX Word Count.WordCount
reloading plugin LaTeXing.LaTeXing
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in C:\Users\deni\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 17, in <module>
  File "/Development/latexing/cache.py", line 19, in <module>
  File "/Development/latexing/api/mendeley.py", line 9, in <module>
  File "C:\Users\deni\AppData\Roaming\SUBLIM~1\Packages\REQUES~1\all\requests_oauthlib\__init__.py", line 3, in <module>
    from .oauth2_auth import OAuth2
  File "C:\Users\deni\AppData\Roaming\SUBLIM~1\Packages\REQUES~1\all\requests_oauthlib\oauth2_auth.py", line 3, in <module>
    from oauthlib.oauth2 import is_secure_transport
ImportError: cannot import name is_secure_transport
reloading plugin Local History.LocalHistory
reloading plugin LocalVariable.detach_variable
reloading plugin LocalVariable.extract_variable
reloading plugin LocalVariable.local_variable
reloading plugin LocalVariable.rename_variable
reloading plugin Markdown HTML Preview.MarkdownHtmlPreview
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin Material Theme.MT
reloading plugin Method.commands
reloading plugin Method.context
reloading plugin Method.method
reloading plugin MultiEditUtils.MultiEditUtils
reloading plugin MultiEditUtils.selection_fields
reloading plugin oauthlib.__init__
reloading plugin oauthlib.common
reloading plugin oauthlib.uri_validate
reloading plugin Open URL.example
reloading plugin Open URL.open_url
reloading plugin OpenPath.open_path
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev.build_sys_dev
reloading plugin PackageDev.commands_file_dev
reloading plugin PackageDev.completions_dev
reloading plugin PackageDev.file_conversion
reloading plugin PackageDev.settings_dev
reloading plugin PackageDev.snippet_dev
reloading plugin PackageDev.syntax_def_dev
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin Pandoc Academic.PandocConvertor
reloading plugin Pandoc Academic.Table_pandoc
reloading plugin Pandoc Referencer.PandocInsertRef
reloading plugin Pandoc Referencer.PandocReferencr
reloading plugin Pandoc.Pandoc
reloading plugin Pandown.minify_json
reloading plugin Pandown.pandownBuildCommand
reloading plugin Pandown.pandownCriticPreprocessor
reloading plugin Pandown.pandownProcess
reloading plugin Pandown.pandownTouchProjectConfigCommand
reloading plugin Quickfind.quick_find
reloading plugin QuickSearchEnhanced.commands
reloading plugin QuickSearchEnhanced.quick_search
reloading plugin R-Box.completions
reloading plugin R-Box.hints
reloading plugin R-Box.linter
reloading plugin R-Box.main_menu
reloading plugin R-Box.source_prompt
reloading plugin R-Box.util
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SnippetCaller.commands
reloading plugin SnippetCaller.indented_selection
reloading plugin SnippetCaller.last_assigned_variable
reloading plugin SnippetCaller.listener
reloading plugin SnippetCaller.selection
reloading plugin SnippetCaller.snippet_caller
reloading plugin SnippetCaller.snippet_info
reloading plugin SnippetMaker.snippet_maker
reloading plugin Statement.commands
reloading plugin Statement.parser
reloading plugin Statement.statement
reloading plugin StatusMessage.commands
reloading plugin StatusMessage.default_status
reloading plugin StatusMessage.status_message
reloading plugin SublimeEnhancedUtilitiesSet.commands
reloading plugin SublimeEnhancedUtilitiesSet.go
reloading plugin Theme - Aprosopo.set_theme
reloading plugin Typewriter.Typewriter
reloading plugin WordCount.WordCount
reloading plugin WordHighlight.word_highlight
reloading plugin Wrap Plus.wrap_plus
reloading plugin CiteBibtex.CiteBibtex
reloading plugin Citer.citer
reloading plugin EncodingHelper.EncodingHelper

reloading plugin orgmode.help_it
reloading plugin orgmode.navigation_history
reloading plugin orgmode.orgmode
reloading plugin orgmode.orgmode_store
reloading plugin sublime-text-markmon.commands
reloading plugin sublime-text-markmon.markmon
reloading plugin sublime-text-markmon.MarkmonListener
reloading plugin sublime-text-markmon.util
reloading plugin SublimeAStyleFormatter.AStyleFormat
plugins loaded
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in C:\Users\deni\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 81, in run
PermissionError: [WinError 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 'C:\\Users\\deni\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\PackageDev.sublime-package'

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 706, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Pandoc Academic.PandocConvertor.PandocConvertorCommand object at 0x000001A50F0C3438>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 706, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Pandoc Academic.PandocConvertor.PandocConvertorCommand object at 0x000001A50F0C3438>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 706, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Pandoc Academic.PandocConvertor.PandocConvertorCommand object at 0x000001A50F0C3438>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 706, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Pandoc Academic.PandocConvertor.PandocConvertorCommand object at 0x000001A50F0C3438>)
```

**Comment by dbobak** [comment]
I've found the solution here: [https://github.com/LaTeXing/LaTeXing/issues/111](https://github.com/LaTeXing/LaTeXing/issues/111)

1) browse packages directory -> remove the folders oauthlib and requests-oauthlib
1a) remove oauthlib from package control settings
2) remove Mediawiker (in my case, also Latexing) with package control
2a) restart sublime
3) install Mediawiker with package control
4) restart sublime - check the console for errors

**Comment by tosher** [comment]
Thanks for the info! Interesting problem.. will check it,

**Comment by dbobak** [comment]
I've noticed another error in console log:
```
Error loading scope:text.html: Unable to find syntax file for scope text.html in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:text.tex.math: Unable to find syntax file for scope text.tex.math in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.actionscript: Unable to find syntax file for scope source.actionscript in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.latex: Unable to find syntax file for scope source.latex in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.xml: Unable to find syntax file for scope source.xml in Packages/Mediawiker/MediawikiNG.sublime-syntax
```
But the plugin is working without noticeable problems.

**Comment by tosher** [comment]
It's not an error, just notice about missing syntax definitions in your ST environment.
If you will install them, messages must disappear.
P.S. If you don't use this syntaxes in code blocks, you can ignore them.

**Comment by dbobak** [comment]
Oh, ok. Thanks :)

**Comment by pahles** [comment]
@dbobak I cannot solve the problem using your "solution". What do I do in step 1a? I can't find oauthlib in package control settings. If I remove Mediawiker with Package Control and try to close ST it hangs and I have to Force Quit it. After starting ST and install Mediawiker again the problem is still there.

I'm using a Mac BTW.

**Comment by tosher** [comment]
https://github.com/LaTeXing/LaTeXing/issues/111#issuecomment-77160524

**Comment by tosher** [comment]
Do you have some plugins with oauth2 folder inside (oauth2, lib/oauth2 or smth.)?

**Comment by pahles** [comment]
No, I started out with a fresh install of ST, just Package Control and then Mediawiker There is no mention of oauthlib in Package Control.sublime-settings.

**Comment by tosher** [comment]
Can you put a dump from ST's console with error messages (better - full console dump)?

**Comment by kiwifreak** [comment]
I have the same problem as pahles. I would be grateful to anyone working on a solution!

**Comment by tosher** [comment]
@kiwifreak, do you have some plugins with oauth2 folder inside (oauth2, lib/oauth2 or smth.)?

**Comment by kiwifreak** [comment]
Yes, I have 
.../Users/Larry/Library/Application Support/Sublime Text 3/Packages/oauthlib/all/oath1
and
....../Users/Larry/Library/Application Support/Sublime Text 3/Packages/oauthlib/all/oath2

**Comment by tosher** [comment]
It's original oauthlib installed as a dependency, it's ok..
Can you show the list of the installed plugins or console dump after sublime start?

**Comment by kiwifreak** [comment]
I have a new problem now: I tried reinstalling Mediawiker (following a friends suggestion) and ST has been in the installation process for about 10 minutes now. Here is the content in the console:

reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'oauthlib' is not currently installed; installing...

**Comment by kiwifreak** [comment]
... still installing ...

**Comment by kiwifreak** [comment]
here it is:

startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/Larry/Library/Application Support/Sublime Text 3/Packages
state path: /Users/Larry/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/Larry/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Mediawiker", "Vintage"]
pre session restore time: 8.0649
first paint time: 8.32786
startup time: 8.33767
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SFTP.SFTP
plugins loaded
reloading plugin 0_package_control_loader.00-package_control
Package Control: Removed directory for unneeded dependency oauthlib
Package Control: Removed directory for unneeded dependency requests
Package Control: The package Mediawiker is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: No updated packages
ignored packages updated to: ["Mediawiker", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'requests' is not currently installed; installing...
Package Control: The dependency 'requests' has successfully been installed or updated
Package Control: The dependency 'oauthlib' is not currently installed; installing...
Package Control: The dependency 'oauthlib' has successfully been installed or updated
Package Control: The dependency 'requests-oauthlib' is not currently installed; installing...
Package Control: The dependency 'requests-oauthlib' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' has successfully been installed or updated
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Mediawiker.mediawiker
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Larry/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 21, in <module>
    from .mwcommands import mw_utils as mw
  File "/Users/Larry/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/__init__.py", line 30, in <module>
    from .mw_configurator import MediawikerConfiguratorCommand
  File "/Users/Larry/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_configurator.py", line 11, in <module>
    import mdpopups
  File "/Users/Larry/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 19, in <module>
    from .st_scheme_template import Scheme2CSS, POPUP, PHANTOM
  File "/Users/Larry/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 22, in <module>
    from pygments.formatters import HtmlFormatter
ImportError: No module named 'pygments'
unexpected rule type, was expecting one of match, include, begin or patterns, got: {comment: unknown source}
unexpected rule type, was expecting one of match, include, begin or patterns, got: {comment: unknown source}
generating syntax summary
generating meta info summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

**Comment by tosher** [comment]
Thanks! It's not the same error, but error. I'm lost another one dependency library "pygments".
I will fix it soon.

**Comment by kiwifreak** [comment]
that would be great, thanks a lot!

**Comment by tosher** [comment]
Please check the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.1.15

**Comment by kiwifreak** [comment]
should I replace the contents of my Mediawiker directory by the contents of this file?

**Comment by tosher** [comment]
After some period of time, Package control will catch the new version and install the updated plugin (on next start) or you can call 'Upgrade package' without restart.

**Comment by kiwifreak** [comment]
Yes, it works! Thanks a lot! 
One last question: the upgraded Mediawiker directory is currently in my downloads folder. Can I just move it to the other ST directories, or will that mess up things again?

**Comment by tosher** [comment]
After upgrade with Package Control it must be in `/Users/Larry/Library/Application Support/Sublime Text 3/Packages/Mediawiker/` - in both variants - upgrade after restart or upgrade by `Upgrade package` command.

**Comment by tosher** [comment]
With manual update, all must be overwritten, except file `package-metadata.json` - don't delete it.

**Comment by kiwifreak** [comment]
Thanks!
