### ISSUE TITLE
Syntax problem when using <syntaxhighlight>under a list

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#103]
A picture ...

![screenshot5](https://cloud.githubusercontent.com/assets/5116363/20180935/1191a2ac-a765-11e6-918e-901252bbcd16.png)

As you can see in line 56, the syntax highlighting is not working properly under the list.
while on line 46 it's working properly.

**Comment by tosher** [comment]
Will fix it..

**Comment by tosher** [comment]
Please check the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.1.15

**Comment by rabin-io** [comment]
Thanks, seems like it resolved my problem.
