### ISSUE TITLE
Reduce connect timeout

### ISSUE THREAD

**Issue by smanolloff** [tosher/Mediawiker#106]
Hi, I noticed that the timeout is too high and when the host is down / network connection is not good / URL in config is wrong / etc., sublime **freezes** for a long time (i think 60 seconds) until it returns an error:
```
Connection failed for ('http', '192.168.56.2:80'): HTTPConnectionPool(host='192.168.56.2', port=80): Max retries exceeded with url: /mediawiki/api.php (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1121fc6d0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```
Maybe anything above 10 seconds is just too much, given the blocking nature of this operation.

**Comment by tosher** [comment]
Please try it with the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.1.17

**Comment by smanolloff** [comment]
Still the same -- I intentionally put a wrong IP address and, unfortunately, sublime freezed again (for around 80 seconds) before displaying a popup error. Not only that, but after clicking "OK" it seems to retry once more and freezes again, for ~80 seconds (no idea where does this value come from. My wiki config section is as follows:

```json
  "mediawiki_site":
  {
    "Simo's Wiki":
    {
      "domain": "",
      "host": "192.168.56.3:80",
      "https": false,
      "pagepath": "/wiki/",
      "password": "mu6ama",
      "path": "/mediawiki/",
      "username": "Simeon",
      "retry_timeout": 5
    }
  }
```
Am I doing anything wrong?
I completely removed and installed Mediawiker just to make sure i have no local plugin modifications, but still the same.

**Comment by tosher** [comment]
Fix will be soon, testing..

**Comment by tosher** [comment]
Please, check with new version:
https://github.com/tosher/Mediawiker/releases/tag/3.2.0

**Comment by tosher** [comment]
And next:
https://github.com/tosher/Mediawiker/releases/tag/3.3.0
:)

**Comment by smanolloff** [comment]
Thanks, timeout seems to work correctly, output window shows error logs in case I wonder what the problem was... so all looks good, very well done! Cheers 🍺
