### ISSUE TITLE
[Bug] imp.get_suffixes() is deprecated

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#107]
### Summary

I get stack trace when I run Sublime Text.

### Expected behavior

No stack trace in console.

### Actual behavior

```python
reloading plugin Mediawiker.mediawiker
E:\SUBLIM~1\Data\Packages\python-pywin32\st3_windows_x32\win32\lib\pywintypes.py:39: DeprecationWarning: imp.get_suffixes() is deprecated; use the constants defined on importlib.machinery instead
  for suffix_item in imp.get_suffixes():
```

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I run Sublime Text. I saw stack trace in console.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by tosher** [comment]
It's only a deprecation warning from dependency library and cause problems for plugin work.
I have the same too.

**Comment by Kristinita** [comment]
@tosher, why you close issue? Problem not solved for me.

Thanks.

**Comment by tosher** [comment]
Which function not works with this message?
As I said, it's just [deprecation warning](https://pythonz.net/references/named/deprecationwarning/), not error... and it in external component.

**Comment by Kristinita** [comment]
> Which function not works with this message?

Possibly, all works good. But stack trace in console is no good.

Or I need create issue in [**PyWin32**](https://github.com/SublimeText/Pywin32/issues) Sublime Text package?

Thanks.

**Comment by Kristinita** [comment]
@tosher , can we remove this stack trace? I really don't like «garbage» in console.

Thanks.
