### ISSUE TITLE
Image preview with new "phantoms api"

### ISSUE THREAD

**Issue by v217** [tosher/Mediawiker#108]
Something like:
https://cloud.githubusercontent.com/assets/8593000/19837804/fed757de-9ec1-11e6-9c82-8fc857d0863a.PNG

or

https://packagecontrol.io/packages/LaTeX%20Equation%20Preview

Would make Mediawiker even better!

**Comment by tosher** [comment]
It's already done and will be available in next version - it will be not phantoms, but popup preview. Phantoms in thinking stage.. how to show inline images, image size and so on..

**Comment by v217** [comment]
Great! Thank you!

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.2.0
