### ISSUE TITLE
Problem with pages with national characters in title and chrome

### ISSUE THREAD

**Issue by dbobak** [tosher/Mediawiker#109]
I'm using personal mediawiki site and the easiest way of editing pages is by the link in the sidebar, as described in https://github.com/tosher/Mediawiker/wiki/Mediawiker-protocol-handler

The problem appears, when the page contains national characters, for example:
```
Prawdopodobieństwo - koncepcja bayesowska
```

The page opens without problem, when clicked in Firefox, but when I'm trying to edit the page in Chrome, I'm getting the following error:

```
Wiki page Prawdopodobie%C5%84stwo_-_koncepcja_bayesowska is not exists. You can create new..
```

Latest Mediawiker in Sublime Text 3, build 3125, run on Windows 10 Pro, Polish language version.

**Comment by tosher** [comment]
As workaround, please try:
open file `..\Packages\Mediawiker\mwcommands\mw_cli.py`:

before line:
```python
class MediawikerCliCommand(sublime_plugin.WindowCommand):
```
add:
```python
from . import mw_utils as mw
```
before line
```python
sublime.set_timeout(lambda: self.window.run_command('mediawiker_page...
```
add line:
```python
url = mw.strunquote(url)
```
Save and restart ST.

If it helps, i'll include this in next release.

**Comment by dbobak** [comment]
It helps, thanks!

**Comment by tosher** [comment]
Included in the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.0
