### ISSUE TITLE
[Feature request] Package for image preview

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#110]
### 1. Request

Now in Mediawiker [**you make a feature image preview**](https://github.com/tosher/Mediawiker/issues/108).

![Image preview](http://i.imgur.com/BaZ57Eq.png)

It would be nice, if you add similar behavior for `http(s)://example.com/example.jpg` link in any file format type, for example, `.html`, `.md` or `.txt`.

### 2. Justification

Image preview — its useful function, but I can not find packages for Sublime Text for it. I find only [**Sublime-Image-Viewer**](https://github.com/rmaksim/Sublime-Text-2-Image-Viewer), but package not upgrade 5 year and not worked in my Sublime Text Build 3126.

### 3. Desirable behavior

For example, I have in my Markdown text **<http://i.imgur.com/KU2baGb.jpg>** link. I place carriage inside the link → I see phantom with my image like in Mediawiker phantoms.

Thanks.

**Comment by tosher** [comment]
[Hover Image Preview](https://packagecontrol.io/packages/Hover%20Image%20Preview)
