### ISSUE TITLE
"Error loading scope: " messages on start up log

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#111]
After loading ST, and looking on the history of the console, I see this messages.

```
Error loading scope:text.tex.math: Unable to find syntax file for scope text.tex.math in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.actionscript: Unable to find syntax file for scope source.actionscript in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.latex: Unable to find syntax file for scope source.latex in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.xml: Unable to find syntax file for scope source.xml in Packages/Mediawiker/MediawikiNG.sublime-syntax
```

**Comment by tosher** [comment]
With xml - it's a bug and will be fixed in new version..
Other messages can by fixed by installing the relevant plugins, if it needed.
Scopes for non mediawiki syntaxes used for source highlighting with tags `source`, `syntaxhighlight`.

**Comment by rabin-io** [comment]
Is there a way to ignore thus syntax files ?

**Comment by tosher** [comment]
This files are not exists (except xml), no way to ignore it on this moment.
It's known "problem".

**Comment by tosher** [comment]
Ohh, will be fixed some more.. :)
Tex, actionscript, latex, xml.

Tsql - it's syntax from my another plugin TSQLEasy for SQL Server - if it not installed, this error will be printed, because syntax used in this plugin.

**Comment by rabin-io** [comment]
10x

**Comment by tosher** [comment]
Please, try the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.0

**Comment by rabin-io** [comment]
still have this one, 

    Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.sublime-syntax

**Comment by tosher** [comment]
Yes:
"Tsql - it's syntax from my another plugin TSQLEasy for SQL Server - if it not installed, this error will be printed, because syntax used in this plugin."

No way to hide this messages :(
