### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Bluszczokrzew** [tosher/Mediawiker#113]
I have an old machine and often work offline. Unfortunately the plugin tries to connect all the time and makes the editing slow and unconvenient. I want to turn off all the Internet options, and leave just the syntax hightlightning (which is great), but there seems to be no option to do it.

**Comment by rabin-io** [comment]
For that you don't need the package, just add one of the `*.tmLanguage` and apply the syntax when you edit the file.

https://github.com/SublimeText/PackageDev

**Comment by tosher** [comment]
You can try to:
1. Work with files (extension .mediawiki)
2. Turn off `Configurator`/`Tab options`/`Mediawiker is enabled`

I'll think about offline mode.. :)

**Comment by Bluszczokrzew** [comment]
thank you.
I found another package, that seems to highlight syntax only.

https://github.com/jhaubrich/Jesse-s-Sublime-Mods

TR

2017-02-20 23:46 GMT+01:00 tosher <notifications@github.com>:

**Comment by tosher** [comment]
Offline mode was implemented in new version:
https://github.com/tosher/Mediawiker/releases/tag/3.4.0
