### ISSUE TITLE
templates show up in goto anything '@'

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#114]
templates show up as symbols in "goto anything" '@'. I prefer it be limited to section headings as goto-anything is useless with a page with a lot of templates.

**Comment by tosher** [comment]
Thanks, i know about it, will try to fix.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.2

**Comment by reagle** [comment]
Confirmed. Thank you!
