### ISSUE TITLE
Talk page in popup

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#115]
I often want to go to a talk page; if there is one, I sometimes find it in internal links, but if it doesn't exist yet, I have to go through this experience to learn that and there is no easy way to create one.

Could there be a talk page option in the quick pop-up that opens the talk page for an article or creates one (with the appropriate title)?

**Comment by tosher** [comment]
Please, try the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.4

**Comment by reagle** [comment]
I expected this to be in the MediaWiker popup (with open page, internal links, external links etc.), not ST's command palette...?

**Comment by tosher** [comment]
In command palette **Open talk page**

**Comment by reagle** [comment]
Yes, but couldn't it be in mediawiker_edit_panel instead, or in addition to.

**Comment by tosher** [comment]
If you have saved panel in User settings, just open the Configurator => Edit Panel, then **All turn On** or turn on needed points only (`Open talk page`).

**Comment by reagle** [comment]
I don't have an option to enable "Open talk page" in the panel configurator; I checked user and default Mediawiker.sublime-settings and don't see anything there either...?

**Comment by reagle** [comment]
I'm again nuking my config and starting over, and I do now see the option. Thank you!

**Comment by reagle** [comment]
I don't think this works with non-mainspace pages. Opening the talk page of "User:Reagle" opens "Talk:Reagle".

**Comment by tosher** [comment]
Namespaces are supported, but maybe en error occurred somewhere. I'll check it.

**Comment by reagle** [comment]
Here's the MW messages:

```
'''Setup new connection to "English wikipedia".'''
Connecting to https://en.wikipedia.org ..  done.
Login in with authorization type login..  done
Page [[User:Reagle]] was opened successfully from "English wikipedia".
Mediawiker notifications exception: 'NoneType' object has no attribute 'run_command'
Page [[Talk:Reagle]] is not exists. You can create new..
Page [[Talk:Reagle]] was opened successfully from "English wikipedia".
```

**Comment by tosher** [comment]
Please, check in new version:
https://github.com/tosher/Mediawiker/releases/tag/3.4.0

**Comment by reagle** [comment]
thanks for the fix
