### ISSUE TITLE
mediawiker cannot connect if the server is not https

### ISSUE THREAD

**Issue by bitbonk** [tosher/Mediawiker#117]
We have a local Wiki server that is not connected to the internet and it does not run on https. Since some time mediawiker is not able to connect anymore. It seems that https is now on by default but there is no way to disable it.

>Connection failed for ('https', 'mywiki.local'): ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060))

**Comment by tosher** [comment]
Just turn it of for your server in settings:
```
"https": false,
```
