### ISSUE TITLE
Turn off/delay popups

### ISSUE THREAD

**Issue by absay** [tosher/Mediawiker#118]
The popups that come up when the mouse is over certain Wiki markup elements are useful in many instances but they can also be very distracting (and even may cause the Configurator GUI to hide sometimes).

edit: they also won't go away when typing, so they stay there and block the view of the text underneath.

Could there be an option to turn them off completely or at least a setting to adjust its delay?

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.3

**Comment by absay** [comment]
Hi. I've read the changelog. Everything sounds great. But my Sublime isn't updating the package though, and the packagecontrol.io page still reads version 3.3.2.

**Comment by tosher** [comment]
PC needs some time to update :)

**Comment by absay** [comment]
Ah, alright. Looking forward to testing the new version soon then! Thanks a alot!
