### ISSUE TITLE
Crashes ST3 when opening from favorites or history

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#121]
In the past month or so, whenever I open from favorites or history, ST3 (3126) quits. Currently using MW 3.3.1. I can still open those pages from the "open page" dialogue, or by browsing links. Is there a way to capture crash diagnostics to report here?

**Comment by tosher** [comment]
I can't to reproduce this error with ST3.3125.dev or ST3.3126. Maybe, it's a conflict with some other plugins. Cay you attach a list of the plugins, installed in ST?

**Comment by reagle** [comment]
```
	"installed_packages":
	[
		"BracketHighlighter",
		"BufferScroll",
		"Compare Side-By-Side",
		"Copy on Select",
		"External Command",
		"File History",
		"File Rename",
		"FileBrowser",
		"Filter Lines",
		"FontCycler",
		"GitGutter",
		"GitSavvy",
		"Markdown Table Formatter",
		"MarkdownEditing",
		"Mediawiker",
		"Origami",
		"Package Control",
		"RawLineEdit",
		"Sort Lines By Selection",
		"SortBy",
		"Straighten-Quotes",
		"Table Editor",
		"Terminal",
		"Trimmer",
		"UnicodeCompletion",
		"W3CValidators",
		"WordCount",
		"Wrap Plus"
	],
```

However, I still experience the problem when I add everything to "ignored_packages" *except* mediawiker and package control.

**Comment by tosher** [comment]
Hmm, maybe it's a ST's problem. 
I will try to reproduce it. It's on MacOS or not?

https://forum.sublimetext.com/t/st3-crashes-frequently-since-build-3124/23042/44

**Comment by reagle** [comment]
Yes, OSX Capitan. I've tried to selectively ignore or remove packages with very indeterminate and confusing results. 

This morning, I created a new ST3 install (nuked my old one) and mediawiker did crash once, but otherwise didn't have a problem when it was the only plugin. Once I installed bracket highlighter I couldn't use the open from history anymore (crash), and that continued to be the case even after I remove bracket highlighter. This page seems to cause problems a lot:

https://en.wikipedia.org/wiki/User:Reagle/QICs

**Comment by reagle** [comment]
At work today, open from history didn't work. It's the same OS and very similar install. In fact, I keep these two directories synchronized:

```
path = Library/Application Support/Sublime Text 3/Packages/
path = Library/Application Support/Sublime Text 3/Settings/
```

**Comment by reagle** [comment]
I did a complete remove of Mediawiker, BufferScroll, and BracketHighlighter. I reinstalled and configured Mediawiker and everything worked well. I installed BracketHighlighter and ST3 crashes when opening from favorites or history. I remove BracketHighlighter, and ST3 still crashes when opening from favorites or history.

Very frustrating.

**Comment by tosher** [comment]
Hmm, can't to reproduce on Windows, on OSX.. with https://en.wikipedia.org/wiki/User:Reagle/QICs or other pages.

**Comment by reagle** [comment]
Is there anyway to get a log from the plugin so I can better figure out what is triggering it?

**Comment by reagle** [comment]
The problem is intermittent for me, on both my platforms actually. Worked find an hour ago, but not now.

**Comment by reagle** [comment]
When it does work, I see the following, is there a way to redirect this to a log file? Maybe it would show what the problem is.

```
'''Setup new connection to "English wikipedia".'''
Connecting to https://en.wikipedia.org ..  done.
Login in with authorization type login..  done
Page [[User:Reagle/QICs]] was opened successfully from "English wikipedia".
Page [[User:Reagle]] was opened successfully from "English wikipedia".
```

**Comment by tosher** [comment]
It's only result messages from plugin.. but problem fires somewhere inside ST.
Can you try dev version of ST3?

**Comment by reagle** [comment]
I'm running stable 3126. The last dev version is 3125. I can install it if you'd like but it doesn't seem any newer.

**Comment by tosher** [comment]
I'm asked about it, because I'm using dev version permanently with BracketHighlighter, Mediawiker and many other plugins and don't have this problem.
Maybe, checks with dev version will can to reduce the problem scope, for example to version 3126 only :)

**Comment by reagle** [comment]
I installed 3125 and sadly had the same problem.

**Comment by reagle** [comment]
So far, I'm finding that deleting ST's cache and index works well. We'll see how long that serves me. Hopefully the problem won't recur.

**Comment by reagle** [comment]
Nope, it is back and deleting cache and index don't help.

**Comment by reagle** [comment]
Also tried 3124, intermittent problem persists. Version 3114 is too old.

**Comment by reagle** [comment]
I doubt this will help, but these are the warnings when MW successfully loads https://en.wikipedia.org/wiki/User:Reagle/QICs

```
Error loading scope:source.ini: Unable to find syntax file for scope source.ini in Packages/Mediawiker/MediawikiNG.sublime-syntax
Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.sublime-syntax
rule scope:source.clojure##anon_string_3 has a scope name, but is unreachable, so the name will never be used
rule scope:source.asp##anon_inside_block_2 has a scope name, but is unreachable, so the name will never be used
rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used
Warning: Page has en unclosed element of type HeaderThree at position 424028, force closing at 424032..
Unable to decode Packages/Mediawiker/img/gutter_h1.png
```

**Comment by tosher** [comment]
First five lines you can ignore, this are standard warnings about some "errors" in syntax files. It's not an important thing.

`Warning` => Just put `Enter` after last empty header and this warning will disapear (headings must be ended with new-line character). It's a warning from plugin's parser.

`gutter_h1.png` - not important too, just unfound image. I'll add it in next release.

Which type of authorization you are using? If `cookies`, which browser?

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.3.6
Fixed gutter and some another errors.

**Comment by reagle** [comment]
New crash scenario (with 3.3.6) when I have a notification and I attempt a load via history/favorites: ST loads the requested page from favorites, shows me the "you have new notifications" dialog, which, when I dismiss, ST3 crashes.

The interesting thing is that I can see the article, so the trigger is something that happens after the dismissal of the notification dialog.

----

BTW: When I load it manually (via 'open page' and type in the page title) I see this in the MW log at the bottom:

```
'''Setup new connection to "English wikipedia".'''
Connecting to https://en.wikipedia.org ..  done.
Login in with authorization type login..  done
Page [[User:Reagle]] was opened successfully from "English wikipedia".
Mediawiker notifications exception: 'MediawikerShowPageCommand' object has no attribute 'window'
```

**Comment by reagle** [comment]
```
		"English wikipedia":
		{
			"authorization_type": "login",
			"cookies_browser": "chrome",
			"domain": "",
			"host": "en.wikipedia.org",
			"http_auth_login": "",
			"http_auth_password": "",
			"https": true,
			"is_ssl_cert_verify": true,
			"is_wikia": false,
			"oauth_access_secret": "",
			"oauth_access_token": "",
			"oauth_consumer_secret": "",
			"oauth_consumer_token": "",
			"pagepath": "/wiki/",
			"password": "XXX",
			"path": "/w/",
			"preview_custom_head":
			[
			],
			"proxy_host": "",
			"retry_timeout": 30,
			"show_red_links": false,
			"use_http_auth": false,
			"username": "Reagle"
		},
```

**Comment by tosher** [comment]
Notifications fix:
https://github.com/tosher/Mediawiker/releases/tag/3.3.7

**Comment by reagle** [comment]
This seems to break my ability to use the MW panel.

```
reloading plugin Mediawiker.mediawiker
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 19, in <module>
    from .mwcommands import mw_utils as mw
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/__init__.py", line 13, in <module>
    from .mw_get_notifications import MediawikerNotificationsCommand, MediawikerGetNotificationsCommand
ImportError: cannot import name MediawikerGetNotificationsCommand
```

**Comment by tosher** [comment]
Ohh, sorry.. will fix it now.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.3.8

**Comment by reagle** [comment]
I still only see 3.3.7 in package control.

**Comment by tosher** [comment]
Now, is available.

**Comment by reagle** [comment]
I can use MW again, and perhaps the notifications issue is fixed but ST still usually crashes when opening from favorites or history.

**Comment by tosher** [comment]
Please try:
* open `mediawiker.py`
* edit lines 66, 67:
```python
        # panel = mw.InputPanelPageTitle(callback=self.page_open)
        # panel.get_title(title)
        self.page_open(title)
```
(comment 2 lines and add one line `self.page_open(title)`)
`Note!` After this changes opening pages with `open page` dialogue will not work.

Try to open pages from pages history or favorites list..

**Comment by reagle** [comment]
Did so and sadly still have intermittent crashes when using favorites/history.

**Comment by tosher** [comment]
It was the only difference between opening with `Open page` dialogue and open from history/favorites :(

**Comment by reagle** [comment]
So weird, thanks for the attempt.

**Comment by tosher** [comment]
Dev version of ST was updated to 3128

**Comment by reagle** [comment]
No change, but I've been monkeying around with the config and might be seeing progress. I used to have:

```
		"English wikipedia":
		{
			"authorization_type": "login",
			"cookies_browser": "chrome",
			"host": "en.wikipedia.org",
			"http_auth_login": "",
			"http_auth_password": "",
			"password": "XXX",
			"username": "Reagle"
		},
```
I emptied the `password` field, kept `username`, but then also filled in `http_auth_login` and `http_auth_password`. I haven't had a crash yet (I hope it lasts).

----

Also, I haven't gotten cookies to work, but if the above continues to work, I'm not worrying about it for a while!

**Comment by reagle** [comment]
What about the index? I disabled it and still got a crash, but when I had the bug of templates {{}} appear in my goto ST3 didn't crash back then. How could I go back to that version and test it?

**Comment by tosher** [comment]
Index? Which index? :)

**Comment by reagle** [comment]
The index of symbols for ST's goto function. I was thinking maybe something with that parsing is prompting a  ST3 crash. I just did another clean install and have a minimal set of packages:

```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"File History",
		"Mediawiker",
		"Package Control"
	]
}
```

Still get intermittent crash. It will work and load a page from favorites/history fine one time, then crash the next.

**Comment by reagle** [comment]
FYI: I went back to MW3.2 and that didn't help.

**Comment by tosher** [comment]
Just another one check:
in `mwcommands/mw_colapse.py` remove all lines like:
```python
gutter_png = mw.from_package(...
```
with
```python
gutter_png = ''
```
Restart ST and check the crash.

**Comment by reagle** [comment]
I did that, did about 3 opens from favorites/history across 5 different restarts and all was well. But eventually it crashed. It is weird, the intermittent work/fail is very clumpy. Once it fails/crashes, it does it for a while.

I could send you my `/Application Support/Sublime Text 3` directory zipped up if you think that could help?

**Comment by tosher** [comment]
With [new version](https://github.com/tosher/Mediawiker/releases/tag/3.3.9), the same result?

**Comment by tosher** [comment]
Directory no needs, maybe settings files from User folder - settings from ST and Mediawiker/BracketHighlighter.

**Comment by reagle** [comment]
I'll see how 3.3.9 goes, but failing that, do you have a public email address? Mine is on my [homepage](http://reagle.org/joseph/).

**Comment by reagle** [comment]
Crashed. Sometimes I find that OSX color pinwheel spins, sometimes not. This time it seemed to spin, go away for a fraction of a second, and then ST3 crashed.

**Comment by reagle** [comment]
Here's some user settings.
[User.zip](https://github.com/tosher/Mediawiker/files/925984/User.zip)

**Comment by reagle** [comment]
Here is a zip of the crash dump/dmp file, but I don't know how to read it yet.

[6DB9BD6C-9F6D-4643-831C-4279562C71D4.zip](https://github.com/tosher/Mediawiker/files/926575/6DB9BD6C-9F6D-4643-831C-4279562C71D4.zip)

**Comment by reagle** [comment]
Left a [message on the ST forum](https://forum.sublimetext.com/t/st3-crashing-with-mediawiker/27623).

**Comment by reagle** [comment]
Trying dev version 3136 and it still happens.

**Comment by tosher** [comment]
May it's out of memory error? 
I don't have any crashes, but work with it everyday.. very strange :(

**Comment by reagle** [comment]
How would I know if that is the type of error?

**Comment by tosher** [comment]
https://support.apple.com/en-us/HT201464
You can try to check the free memory and memory using by ST periodically.

**Comment by reagle** [comment]
I opened the activity monitor and ST3 showed at 115MB; opened a favorite, it succeeded, showed 66MB for a second, and then stable at 264MB; closed at 261MB; tried to open another and ST3 quit. Didn't see anything too weird.

```
Mach Virtual Memory Statistics: (page size of 4096 bytes)
Pages free:                               24495.
Pages active:                            312381.
Pages inactive:                          252458.
Pages speculative:                         4291.
Pages throttled:                              0.
Pages wired down:                       1226735.
Pages purgeable:                          22241.
"Translation faults":                1150451825.
Pages copy-on-write:                   48705213.
Pages zero filled:                    498396866.
Pages reactivated:                     53072870.
Pages purged:                          21251784.
File-backed pages:                       124736.
Anonymous pages:                         444394.
Pages stored in compressor:             8080083.
Pages occupied by compressor:            276393.
Decompressions:                        77975131.
Compressions:                         139797950.
Pageins:                               50058443.
Pageouts:                               1267992.
Swapins:                                5979088.
Swapouts:                               6944439.
```

**Comment by tosher** [comment]
`Reopen page` command work ok?

**Comment by reagle** [comment]
I discovered something weird. I wanted to run ST3 from the terminal so I could see any error messages when it closed. However, `/usr/local/bin/subl file.txt` always goes to the background.  

So I created a dummy file `foo.txt` and opened with the wait option: `/usr/local/bin/subl -w foo.txt`.
As long as I do not close the tab for `foo.txt` within ST3, I do not get my prompt back in my terminal. **Also**, as long as I keep the `foo.txt` tab open, I can open favorites and history perfectly!

I did this dozens of times, opening articles from history, and it always worked as long as I keep the `foo.txt` tab open.
I then closed the tab for `foo.txt`; ST3 then gave me my prompt back in terminal. I then opened something from my history, and ST3 disappeared! Again, ST3's exit is not *guaranteed*, it's closing is always intermittent. 

Very weird. I'll keep experimenting to see if I can continue to replicate or figure anything else out.

**Comment by reagle** [comment]
I just replicated this above.

- open sublime, open bookmark, crash
- open sublime, open bookmark, crash
- open sublime, open bookmark, crash
- `/usr/local/bin/subl -w foo.txt`
  - open bookmark, works, close article tab
  - open bookmark, works, close article tab
  - open bookmark, works, close article tab
  - close foo.txt
  - open bookmark, works, close article tab
  - open bookmark, works, close article tab
- I quit
- open sublime, open bookmark, crash
- open sublime, open bookmark, crash

Of course, when it "crashes" when I open a bookmark, I'm not sure that it is crashing or exiting for some other reason.

**Comment by tosher** [comment]
If you make:
* Disable BracketHighlighter 
* Open bookmark
* Enable BracketHighlighter 
Crash?

**Comment by reagle** [comment]
Uninstalling and disabling BracketHighlighter makes no difference.

**Comment by reagle** [comment]
Having another tab or pane open does seem to help keep it from exiting/crashing...

**Comment by tosher** [comment]
Yarrr, i catch the same error on MacOS :)
Some moments:
* Not crashed if we have a opened tab
* Not crashed if we have opened project in sidebar
* Not crashed with option `"close_windows_when_empty": true`
You have the same effects?

**Comment by reagle** [comment]
Yea! I'm not crazy :-)

Yes, having a tab, sidebar, or that setting do seem to keep it from crashing/exiting.

I wonder if it is related to SublimeTextIssues/Core/issues/1252 ?

**Comment by reagle** [comment]
@tosher any idea what is causing the problem?

**Comment by reagle** [comment]
Just tested with 3.0 and unfortunately still present.

**Comment by tosher** [comment]
I think it must be fixed in ST3 core, I can't to fix it on plugin's level :(

**Comment by reagle** [comment]
Is the bug reported with the core developers? (I'm not sure how to do so.)

**Comment by tosher** [comment]
You point it in https://github.com/tosher/Mediawiker/issues/121#issuecomment-315843003 :)

**Comment by reagle** [comment]
That was just a guess, I have "close_windows_when_empty" set as false, and that issue was closed as solved. As the plugin developer, would you be willing to open an issue with Core? I think you are in the best position to document what is going on.

**Comment by tosher** [comment]
You can reopen the issue on SublimeTextIssues if it is critical. 
As plugin developer I haven't best position because of users are more important :) And I haven't access to core, it's closed for us - only API is available.

**Comment by reagle** [comment]
@tosher, please see response in new issue.

**Comment by reagle** [comment]
Using ST3 build 3.1.4.3 and this problem no longer occurs! No idea why, but I'll take it. Closing issue and I hope it doesn't recur.
