### ISSUE TITLE
No feedback on failed post

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#122]
Mediawikier doesn't warn the user that attempts to post or save had failed. If you open a console, you will see the following, but that's only if you look.

```
Mediawiker.lib.mwclient.errors.UserBlocked: ('DeltaQuad', '{{colocationwebhost}}: Spam issues confirmed by CU (Also proxy hosting)')
```

**Comment by tosher** [comment]
Please checks with new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.6

**Comment by reagle** [comment]
Using a VPN, the console shows and exception, but MW still incorrectly reports as success and gives no prominent user warning.

```
UserBlocked exception: ('Slakr', '{{colocationwebhost}}')
Page [[User:Reagle/Bio-factoids]] was successfully published to wiki "English wikipedia".
```

**Comment by tosher** [comment]
It's will be fixed in next version.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.4.5
