### ISSUE TITLE
Hover/open dialog can't open relative links?

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#123]
When I hover over a link like  [[/Bio-factoids| verified factoids]] I am not given the option to open. Does MW not understand relative links?

**Comment by tosher** [comment]
`Subpages` - is not default option and currently unsupported.
I wll try to implement it.

**Comment by reagle** [comment]
Okay, not a biggie, I didn't know if it was a bug.

BTW: I like to edit mostly via keyboard. Is there a way to prompt a pop-up via keyboard, rather than hover, or at least have the open link appear in 'context_menu' command, which I have bound to a key stroke?

**Comment by tosher** [comment]
Easy to make popup firing, but not easy to make keyboard navigation inside popup.
For keyboard using, needs to implement alternative quick menu instead of popups.

**Comment by reagle** [comment]
I get a pop-up over relative links now, but in this case it is showing as red...?

<img width="806" alt="screen shot 2017-04-17 at 2 27 00 pm" src="https://cloud.githubusercontent.com/assets/596814/25099373/ff72db5e-2379-11e7-87bf-a35089dbaadb.png">

**Comment by tosher** [comment]
As I said earlier, subpages doesn't supported now. This link is just a normal page with name `/QICs`, this page not exists in wiki and shown as red.

**Comment by reagle** [comment]
Oh, sorry.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.4.1
