### ISSUE TITLE
[Bug] JS2Coffee conflict

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#124]
### 1. Summary

If I run commands of [**JS2Coffee**](https://packagecontrol.io/packages/JS2Coffee) package, if Mediawiker enable, I get error popup and some packages don't work for me.

### 2. Settings

My `Gruntfile.js` file:

```javascript
// @Author: Kristinita
// @Date:   2017-04-05 20:11:18
// @Last Modified time: 2017-04-11 08:20:09
module.exports = function(grunt) {


    grunt.loadNpmTasks('grunt-shell');
    grunt.loadNpmTasks('grunt-move');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-text-replace');
    grunt.loadNpmTasks('grunt-jsbeautifier');

    grunt.initConfig({
        ///////////////////
        // Pelican build //
        ///////////////////
        // http://manos.im/blog/static-site-pelican-grunt-travis-github-pages/
        // https://github.com/sindresorhus/grunt-shell
        shell: {
            generate: {
                command: 'pelican content -s pelicanconf.py'
            },
            deploy: {
                command: 'pelican content -s publishconf.py'
            }
        },
        //////////////////////////////////
        // Move files to another folder //
        //////////////////////////////////
        // https://www.npmjs.com/package/grunt-move
        move: {
            options: {
                ignoreMissing: true,
                moveAcrossVolumes: true
            },
            // Favicons
            favicons: {
                src: 'output/favicons/*',
                dest: 'output/'
            },
            // HTML, which I need to move in root folder
            roothtml: {
                src: 'output/root-html/*',
                dest: 'output/'
            },
            // Different file types
            extra: {
                src: 'output/extra/*',
                dest: 'output/'
            },
        },
        //////////////////////////
        // Delete blank folders //
        //////////////////////////
        // https://github.com/gruntjs/grunt-contrib-clean
        clean: ['output/extra', 'output/favicons', 'output/root-html'],
        //////////////////
        // Replace text //
        //////////////////
        // https://github.com/yoniholmes/grunt-text-replace
        replace: {
            replacehtml: {
                src: ['output/**/*.html'],
                overwrite: true,
                replacements: [
                    // Incorrect paths for personal CSS and JavaScript,
                    // https://github.com/mortada/pelican_javascript/issues/3
                    {
                        from: 'css/personal',
                        to: '../css/personal'
                    },
                    // Fancybox images,
                    // With regex: https://github.com/yoniholmes/grunt-text-replace#usage
                    {
                        from: /<img alt="(.+?)" src="(.+?)" \/>/g,
                        to: '<a class="fancybox" href="$2"><img src="$2" alt="$1"></a>'
                    },
                    // Cllipboard.js,
                    // http://ru.stackoverflow.com/a/582520/199934
                    // http://stackoverflow.com/a/33758293/5951529
                    {
                        from: /<pre><code class="(.+?)">((.|\n|\r)+?)<\/code><\/pre>/g,
                        to: '<pre><code data-language="$1">$2</code><button class="SashaButton SashaTooltip"><img src="../images/interface_images/clippy.svg" alt="Clipboard button" width="13"></button></pre>'
                    },
                ]
            }
        },
        ///////////////////
        // js-beautifier //
        ///////////////////
        // https://github.com/vkadam/grunt-jsbeautifier
        jsbeautifier: {
            files: ["output/**/*.html"],
        },
    });

    grunt.registerTask('build', ['shell:generate', 'move', 'clean', 'replace']);
    grunt.registerTask('publish', ['shell:deploy', 'move', 'clean', 'jsbeautifier', 'replace']);
};
```

### 3. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install Mediawiker → I install JS2Coffee → I restart Sublime Text → I open `Gruntfile.js` → <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `JS2Coffee: Convert & Make New File`.

### 4. Expected behavior

If Mediawiker disabled for me, I get [**successful conversion**](http://js2.coffee/#try:%2F%2F%20%40Author%3A%20Kristinita%0A%2F%2F%20%40Date%3A%20%20%202017-04-05%2020%3A11%3A18%0A%2F%2F%20%40Last%20Modified%20time%3A%202017-04-11%2008%3A20%3A09%0Amodule.exports%20%3D%20function(grunt)%20%7B%0A%0A%0A%20%20%20%20grunt.loadNpmTasks(%27grunt-shell%27)%3B%0A%20%20%20%20grunt.loadNpmTasks(%27grunt-move%27)%3B%0A%20%20%20%20grunt.loadNpmTasks(%27grunt-contrib-clean%27)%3B%0A%20%20%20%20grunt.loadNpmTasks(%27grunt-text-replace%27)%3B%0A%20%20%20%20grunt.loadNpmTasks(%27grunt-jsbeautifier%27)%3B%0A%0A%20%20%20%20grunt.initConfig(%7B%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20Pelican%20build%20%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20http%3A%2F%2Fmanos.im%2Fblog%2Fstatic-site-pelican-grunt-travis-github-pages%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20https%3A%2F%2Fgithub.com%2Fsindresorhus%2Fgrunt-shell%0A%20%20%20%20%20%20%20%20shell%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20generate%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20command%3A%20%27pelican%20content%20-s%20pelicanconf.py%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20deploy%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20command%3A%20%27pelican%20content%20-s%20publishconf.py%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20Move%20files%20to%20another%20folder%20%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Fgrunt-move%0A%20%20%20%20%20%20%20%20move%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20options%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ignoreMissing%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20moveAcrossVolumes%3A%20true%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Favicons%0A%20%20%20%20%20%20%20%20%20%20%20%20favicons%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20src%3A%20%27output%2Ffavicons%2F*%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dest%3A%20%27output%2F%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20HTML%2C%20which%20I%20need%20to%20move%20in%20root%20folder%0A%20%20%20%20%20%20%20%20%20%20%20%20roothtml%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20src%3A%20%27output%2Froot-html%2F*%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dest%3A%20%27output%2F%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Different%20file%20types%0A%20%20%20%20%20%20%20%20%20%20%20%20extra%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20src%3A%20%27output%2Fextra%2F*%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dest%3A%20%27output%2F%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20Delete%20blank%20folders%20%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20https%3A%2F%2Fgithub.com%2Fgruntjs%2Fgrunt-contrib-clean%0A%20%20%20%20%20%20%20%20clean%3A%20%5B%27output%2Fextra%27%2C%20%27output%2Ffavicons%27%2C%20%27output%2Froot-html%27%5D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20Replace%20text%20%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20https%3A%2F%2Fgithub.com%2Fyoniholmes%2Fgrunt-text-replace%0A%20%20%20%20%20%20%20%20replace%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20replacehtml%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20src%3A%20%5B%27output%2F**%2F*.html%27%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20overwrite%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20replacements%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%2F%2F%20Incorrect%20paths%20for%20personal%20CSS%20and%20JavaScript%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%2F%2F%20https%3A%2F%2Fgithub.com%2Fmortada%2Fpelican_javascript%2Fissues%2F3%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20%27css%2Fpersonal%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20%27..%2Fcss%2Fpersonal%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Fancybox%20images%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20With%20regex%3A%20https%3A%2F%2Fgithub.com%2Fyoniholmes%2Fgrunt-text-replace%23usage%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20%2F%3Cimg%20alt%3D%22(.%2B%3F)%22%20src%3D%22(.%2B%3F)%22%20%5C%2F%3E%2Fg%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20%27%3Ca%20class%3D%22fancybox%22%20href%3D%22%242%22%3E%3Cimg%20src%3D%22%242%22%20alt%3D%22%241%22%3E%3C%2Fa%3E%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Cllipboard.js%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20http%3A%2F%2Fru.stackoverflow.com%2Fa%2F582520%2F199934%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20http%3A%2F%2Fstackoverflow.com%2Fa%2F33758293%2F5951529%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20%2F%3Cpre%3E%3Ccode%20class%3D%22(.%2B%3F)%22%3E((.%7C%5Cn%7C%5Cr)%2B%3F)%3C%5C%2Fcode%3E%3C%5C%2Fpre%3E%2Fg%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20%27%3Cpre%3E%3Ccode%20data-language%3D%22%241%22%3E%242%3C%2Fcode%3E%3Cbutton%20class%3D%22SashaButton%20SashaTooltip%22%3E%3Cimg%20src%3D%22..%2Fimages%2Finterface_images%2Fclippy.svg%22%20alt%3D%22Clipboard%20button%22%20width%3D%2213%22%3E%3C%2Fbutton%3E%3C%2Fpre%3E%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20js-beautifier%20%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20%20%20%20%20%2F%2F%20https%3A%2F%2Fgithub.com%2Fvkadam%2Fgrunt-jsbeautifier%0A%20%20%20%20%20%20%20%20jsbeautifier%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20files%3A%20%5B%22output%2F**%2F*.html%22%5D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%3B%0A%0A%20%20%20%20grunt.registerTask(%27build%27%2C%20%5B%27shell%3Agenerate%27%2C%20%27move%27%2C%20%27clean%27%2C%20%27replace%27%5D)%3B%0A%20%20%20%20grunt.registerTask(%27publish%27%2C%20%5B%27shell%3Adeploy%27%2C%20%27move%27%2C%20%27clean%27%2C%20%27jsbeautifier%27%2C%20%27replace%27%5D)%3B%0A%7D%3B%0A). Not errors, stack trace, popups.

### 5. Actual behavior

If Mediawiker enabled for me, I get popup:

![Popup](http://i.imgur.com/uWS8Ckh.png)

Sublime Text console output:

```json
command: js_coffee {"new_file": true}
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

Some packages, for example, Package Control & [**Suricate**](https://packagecontrol.io/packages/Suricate) packages don't work for me. I need restart Sublime Text.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**Package:**
I use the latest stable version of this package for Sublime Text 3

Thanks.

**Comment by tosher** [comment]
I can't to check this environment now, but make one fix.. maybe it fixes this:
https://github.com/tosher/Mediawiker/releases/tag/3.3.9

**Comment by Kristinita** [comment]
Thanks, now I don't get this problem!
