### ISSUE TITLE
Pages history

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#125]
When I use the MW panel item "Pages history" it just reopens the page again in a new tab. What is it supposed to do? Page preview similarly does nothing other than spin the color wheel for a second.

**Comment by tosher** [comment]
Please check the new version:
https://github.com/tosher/Mediawiker/releases/tag/3.3.9

**Comment by reagle** [comment]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_preview_page.py", line 76, in run
    page_id_old = self.get_page_id()
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_preview_page.py", line 85, in get_page_id
    first_line = tf.readline()
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4928: ordinal not in range(128)
```

**Comment by tosher** [comment]
Sorry, lost one change, will be in next build..

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.4.0

**Comment by reagle** [comment]
Still nothing happens, and I'm not sure what is supposed to happen. Is it supposed to open a browser window with the selected page's history?

**Comment by tosher** [comment]
Hmm...
* `Page history` just shows the list of pages posted to wiki site. Selecting of an item - open page in editor;
* `Page preview` - opens the page preview in browser (local generated file)

**Comment by reagle** [comment]
`Page preview` now works, thank you. 
My point about `Page history` was a momentary confusion when I thought "Pages history" was going to show me the edit history/log of a page, so when I selected the top/current page and it simply reopened it again I thought it was broken. So my bad.

That said, I wonder if the following might help with consistency:

```
Open page (specify)
Reopen page
Open page from history
Open page from favorites
```

I'm not convinced this would be helpful, but

**Comment by tosher** [comment]
One point/fix.. not `Page history`, but `Pages history` :)
