### ISSUE TITLE
Option to edit just a Subsection of a page

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#128]
Mediawiki API support for section editing, can this option be added to Mediawiker to allow opening/editing just a section and not all the page ?

from: https://www.mediawiki.org/wiki/API:Edit#Parameters
```
Pages can be edited and created with action=edit.
Parameters
title: Title of the page you want to edit. Cannot be used together with pageid. Note: If $wgCapitalLinks is set to false, 'Article' and 'article' will not be considered as the same page, as in Wiktionary, for example.
pageid: Page ID of the page you want to edit. Cannot be used together with title. 1.20+
section: Section number. 0 for the top section, 'new' for a new section. Omit to act on the entire page.
sectiontitle: Title to use if creating a new section. If not specified, summary will be used instead. 1.19+
text: New page (or section) content.
...
```

**Comment by tosher** [comment]
It needs just for big pages or something else?

**Comment by rabin-io** [comment]
Yes that's exactly my use case, some times I edit long wiki pages, like when I write documentation for some project, and it can be useful to only have a sub-set of the page in the editor to focus only on that.

**Comment by reagle** [comment]
@rabin-io that's a general editing problem, not really specific to mediawiki. You could simply fold the other sections. It's also easy to select the text you care about, invert the selection, and fold.

**Comment by rabin-io** [comment]
@reagle yes I know I can fold section, but having the option to edit and save a subset of the page have its own benefits. 
* smaller post updates
* allow safer edit (like when doing a mass search&replace)

this request is more of "nice to have" and not "must have" option.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.4.2

**Comment by rabin-io** [comment]
I'm having problem with this, trying to open the page `Sandbox::1` which should open section 1, will open a new page in sublime. Am I doing something wrong ?

**Comment by tosher** [comment]
No, you absolutely right!
I'm forgot to merge "section" related changes into repo :(
Sorry fot this fault, I'll try to fix it tomorrow.

**Comment by rabin-io** [comment]
thx @tosher for all your hard work, much appreciated 👍

**Comment by tosher** [comment]
Fixed
https://github.com/tosher/Mediawiker/releases/tag/3.4.3

**Comment by rabin-io** [comment]
Thanks, seems to work now.
