### ISSUE TITLE
Browser extension to open file while viewing the wiki page?

### ISSUE THREAD

**Issue by silverl** [tosher/Mediawiker#129]
Just wondering if there is any kind of browser extension which might enable the opening of SublimeText from a wiki page.
Thanks.

**Comment by Plloi** [comment]
Hasn't been updated in awhile so ymmv but there is a user-script in the repo here: https://github.com/tosher/Mediawiker/tree/master/handler/userscript

**Comment by silverl** [comment]
Oh, very interesting! I already have Chrome and Tampermonkey. I installed the script and modified the header for my wikis.

I also had to manually add a protocol handler for mediawiker:// in the Windows Registry.

Clicking the edit button now opens Sublime, but nothing happens. Any clues on what to pass into Sublime and how to go about it?

Thanks.

**Comment by silverl** [comment]
I'm looking all around for a way to invoke the mediawiker open page command from the subl command line tool. Not having luck yet. Wondering if it's possible.

**Comment by silverl** [comment]
Ok, just found this page, working through it: https://github.com/tosher/Mediawiker/wiki/Mediawiker-protocol-handler

**Comment by silverl** [comment]
That was the missing piece of the puzzle. It's working! Thank you!

**Comment by Plloi** [comment]
Glad to hear my extension still works, means I don't have to fix it, yet.
