### ISSUE TITLE
[Feature Request] Option to set user-defined languages for lua/css/js

### ISSUE THREAD

**Issue by RheingoldRiver** [tosher/Mediawiker#132]
Could you add a preference to default to user-defined language or another plugin instead of the default ones? For example I prefer LuaExtended. Thanks! (For now I just edited mw_utils.py directly but a setting would be nice)

**Comment by tosher** [comment]
I think it's possible, will try to add this.

**Comment by tosher** [comment]
Please, try the new version:
https://github.com/tosher/Mediawiker/releases/tag/v3.4.9
