### ISSUE TITLE
[v3.4.9] Observations, Issues, suggestions etc

### ISSUE THREAD

**Issue by TriMoon** [tosher/Mediawiker#134]
Hi it's been a while since i used this extension, and just started to use it again in ST3.
Below are some observations from a fresh user point of view:
1. There is no **default** for wikia (Now FANDOM) type wikis, had to go search to find how to configure it.
2. All **Settings** should be able to be overridden per wiki in user settings.
   1. These should also be able to be set in a **project file**, which overrides user settings...
   2. While inside a settings node the keys should be without the "mediawiker_" prefix for aesthetics/readability and space ...
   1. Example: Favorites are saved inside top settings-node.
**Intuitive use:** This should become a subkey inside the wiki-specific settings.
3. Sometimes opening pages, eg. from favorites, does not open the page but gives an error in console ```TypeError exception for get_page: unorderable types: int() > NoneType()``` must be a time-out?
4. **Pages history** does not get populated, or is unclear what it is supposed to be for...
**Intuitive use:** While working on a wiki, it should list recent pages opened.
5. **Syntax highlighting**
   1. Does not properly recognize parser functions, eg: {{#if:..}} etc are treated as templates and get that kind of popup which is wrong...
      1. HTML with CSS styles used as arguments to parser functions don't get properly highlighted.
For sample data see the source of [Template:Progress](https://trainstation.wikia.com/wiki/Template:Progress).
6. **Preview**
   1. <s>does not take into account the namespace of the page being previewed.
This causes links to templates in Template: namespace to be wrong.</s> -> Only happens for locally opened pages, works ok when page is opened from wiki...
   2. Still trying to get it render like online version, background etc is not good...
7. Maybe more will add as i notice :wink:

**Comment by tosher** [comment]
1. Example for quake.wikia.com:
```json
    "mediawiker_site": 
    {
	"quake.wikia.com":
	{
		"domain": "",
		"host": "quake.wikia.com",
		"https": false,
		"pagepath": "/wiki/",
		"password": "mypassword",
		"path": "/",
		"username": "my-username-at-wikia.com"
	}
    }
```
Username and password - from wikia site, not from facebook or google.

Without credential defining, you can use cookies from browser:
```json
  "authorization_type": "cookies",
  "cookies_browser": "firefox"
```

2. Needs real use-cases and then any option can be moved to per-wiki-settings. 
  i. I think, it's an additional redundant complication for text editing. But... use cases are welcome :)
  ii. `mediawiker_` - maybe in future versions
  iii. Favorites - No user action is required with this settings, it's just a storage.
3. Example (if public)?
4. It's recent pages **published**.
5. Needs examples as blocks of text or as lines from some page.
6. Page Preview command uses wiki api to generate page.
7. You're welcome! :)

**Comment by TriMoon** [comment]
quick reply at @tosher ,

2. I'm working with project files inside ST3 to organize my editing of many things.
   1. Use case as mentioned just above, i use project files for different task, and in this case i use one project called Wiki in which i edit pages on different wiki's, so settings inside the project file will help to keep settings per wiki in it...
   2. This is just a hint to make the settings inside user-settings and project settings be more readable while under a node(object) named mediawiker :wink: 
   3. Same as above, will keep things together inside 1 object/node.
3. It happens with all pages, trying again succeeds without error...
4. Then it should be renamed because current name makes a user get wrong idea of functionality...
5. See the link i gave, it has code and text :wink: 
6. The preview functionality needs more improvement as it is sometimes required to add more as head links.
   a. Eg. Article needs to be inside a nested div inside a body with a certain class etc. to render properly using the CSS from the API call "/load.php?..."
I would suggest a per-wiki setting to configure multiple files, 1 pre-API text and 1 post-API text., to generate the preview output. A single setting as-is-now is just not enough...
7. I really appriciate the work you do :wink:

**Comment by tosher** [comment]
2.iii. I think, multiple level nesting with normalized data - good for inner storage, but for user settings - not. It's hard to understand and support. Only really special settings must be inside per-wiki-options. Or it must be optional. I'll think about it :)
4. Maybe..., but it's an editor, not a viewer :) Maybe, I'll add the ability to save all pages there, as an option.
5. Some fixes will be in the next version. Html&Css with multiline args values, with comments inside, are not supported now.
6. Please, suggest your version of settings. But without external files. With workable for classic wiki site, default options.
7. Thank you! :)

**Comment by tosher** [comment]
5. https://github.com/tosher/Mediawiker/releases/tag/v3.4.10

**Comment by TriMoon** [comment]
>     1. https://github.com/tosher/Mediawiker/releases/tag/v3.4.10

No idea what really changed because the syntax highlighting still looks same, maybe try adding support for [ParserFunctions](https://www.mediawiki.org/wiki/Help:Extension:ParserFunctions)+[StringFunctions](https://www.mediawiki.org/wiki/Extension:StringFunctions), eg: {{#xxx:..}}

**Comment by tosher** [comment]
Before

![default](https://user-images.githubusercontent.com/2726543/47266431-28dc9200-d53f-11e8-8c8b-15c4f84d45e2.png)

After

![default](https://user-images.githubusercontent.com/2726543/47266437-41e54300-d53f-11e8-8c43-d78c9393df01.png)

**Comment by tosher** [comment]
6. It's your current settings, right? It looks like a self-sufficient :) But I'm asked about "what needs to change" and your version of the settings for it :)

**Comment by TriMoon** [comment]
>@tosher 
2.iii. I think, multiple level nesting with normalized data - good for inner storage, but for user settings - not. It's hard to understand and support. Only really special settings must be inside per-wiki-options. Or it must be optional. I'll think about it :)

Could you at least start with allowing the settings to be put inside project files?
That way we can keep the settings inside a central config per project.

**Comment by TriMoon** [comment]
More Project based improvement:
- Ability to open local files and be recognized as page from wiki.
fe. You open a file like ```<project dir>/Trainstation wiki/User:©TriMoon™/Station/Management```
This would recognize this file as being from wiki-setting **Trainstation wiki** and page **User:©TriMoon™/Station/Management**
After editing this local file you should be able to:
   - Check for unsaved differences with server-version
   - Commit the changes to that page.

**Comment by tosher** [comment]
`Maybe you could make your default output use the layout and tag-settings it creates?`

It can be a default for concrete wikia site, not for all. The plugin doesn't have the setting for all sites. We can add an example into project's wiki if you want.

**Comment by TriMoon** [comment]
> > Maybe you could make your default output use the layout and tag-settings it creates?
> 
> It can be a default for concrete wikia site, not for all. The plugin doesn't have the setting for all sites. We can add an example into project's wiki if you want.

That would be a nice thing if it's finished, but no idea when that will be yet.
The script i crafted is setup to allow for user settings, but the layout is for all wikia that uses oasis-skin.

One thing you could add right away now in your extension is the title tag, then i could grab that in my script to display the page name :wink:

**Comment by tosher** [comment]
Done.
https://github.com/tosher/Mediawiker/releases/tag/v3.4.12

**Comment by TriMoon** [comment]
lol i meant the actual ```<title>pagename</title>``` tag inside the head but ill see how to use the var... :rofl:

**Comment by tosher** [comment]
```json
"preview_custom_head": [
    "<title>{{ title }}</title>", 
    "<meta charset=\"UTF-8\"/>",
    "<link rel=\"stylesheet\" href=\"{{ http }}://{{ host }}{{ path }}load.php?debug=false&amp;lang={{ lang }}&amp;modules=site&amp;only=styles&amp;skin=vector\"/>",
    "<link rel=\"stylesheet\" href=\"{{ http }}://{{ host }}{{ path }}load.php?debug=false&amp;lang={{ lang }}&amp;modules={{ geshi_css }}ext.visualEditor.viewPageTarget.noscript|mediawiki.legacy.commonPrint,shared|mediawiki.sectionAnchor|mediawiki.skinning.interface|mediawiki.ui.button|skins.vector.styles&amp;only=styles&amp;skin=vector&amp;*\" />"
 ]
```
With default settings works fine for me.

**Comment by TriMoon** [comment]
No idea why the title didn't work 2 days ago, but seems to be self-fixed in mean time :+1: 
Must be browser updates...(I'm using Firefox Nightly)

**Comment by tosher** [comment]
I'm using Daily :) 
(i know about builds)

**Comment by TriMoon** [comment]
Could you enhance the popups that are displayed for the parser functions so that it includes a link to open the documentation in the browser?

Here are links to respective pages on mediawiki website, that are most used:
1. [mw:ParserFunctions](https://www.mediawiki.org/wiki/Help:Extension:ParserFunctions)
2. [mw:Magic_words](https://www.mediawiki.org/wiki/Help:Magic_words)
3. [mw:StringFunctions](https://www.mediawiki.org/wiki/Extension:StringFunctions)
4. [mw:Variables](https://www.mediawiki.org/wiki/Extension:Variables)

**Comment by TriMoon** [comment]
Just FYI: I removed the old-gist and created a new gist with:
1. [Mediawiker.sublime-settings](https://gist.github.com/TriMoon/f8de90f89e5b70a7e4beb8d89f6b8d17#file-mediawiker-sublime-settings)
Config i use at moment with anonymized parts.
2. [mediawiker_preview_fix.js](https://gist.github.com/TriMoon/f8de90f89e5b70a7e4beb8d89f6b8d17#file-mediawiker_preview_fix-js)
The actual functionality that changes the preview page, using variables set in 3.
(Candidate for inclusion in your extension when ready)
3. [mediawiker_preview_script.js](https://gist.github.com/TriMoon/f8de90f89e5b70a7e4beb8d89f6b8d17#file-mediawiker_preview_script-js)
Configuration file that will set variables for and call the function from 2. like
```Javascript
mediawikerFixPreview(
	'<remote base url>'
	,'<local base url>' // Can be 'File://<local absolute path>'
)
```
4. [mediawiker_preview_style.css](https://gist.github.com/TriMoon/f8de90f89e5b70a7e4beb8d89f6b8d17#file-mediawiker_preview_style-css)
CSS-file that is pulled in by 2.

This will make it easier for others to follow/use what i use, and for me to update parts of it to improve things in due time.
Keep on coding :+1: :rofl:

**Comment by tosher** [comment]
* [x] `These should also be able to be set in a project file, which overrides user settings` 
* [x] `parser-functions and magic-words would be displayed in different colors from template calls by the syntax-highlighting`
* [x] `the keys should be without the "mediawiker_"`
* [x] `the popups that are displayed for the parser functions so that it includes a link to open the documentation in the browser`

Testing..

**Comment by TriMoon** [comment]
Hmm after 2nd though it might be better to have the project settings be applied after the global mediawiker settings but **before** the user settings.
The user settings should always be the highest priority, so the user in question can always override to its own taste...

**Comment by tosher** [comment]
List is consists of your quotes! :)

In Sublime text projects settings always has a higher priority (it's like a tab's settings) - i think it's a correct way.

As example - many sites in user settings, but one site in separated project.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.5.0

**Comment by TriMoon** [comment]
I just checked but:
1. Usersettings are not automatically converted, i did now by hand...
2. Not sure what exactly broke but there is no popups anymore when you hold mouse over text. you get many error messages in console log.
   - I can see some highlighting changes, but they are inconsistent... (Check with the source of my [Template:Progress](https://trainstation.wikia.com/wiki/Template:Progress) )
3. About the project settings **text** in your changelog: "_Project settings support (overrides user settings)_", that last part (...) should be removed to make it become correct, because user settings should override the project settings which override default settings :wink: 
   - The priority is the default sublime priority for project settings (Am i right?)

**Comment by tosher** [comment]
1. Converting fire at the start or on the first call of any setting.
2. Works for me, detailed needed
3. Plugin default settings => Plugin user settings => Project settings
4. `"mediawiker.category_root": "Category:Templates"`. Prefixed settings in projects - is a standard way, as I know.

**Comment by tosher** [comment]
Question, just interesting..
Why not to use one variable per line (just for readability) instead of 
```
{{#vardefine:progress-val | {{{1 | {{{val | {{#var:progress-val|}} }}} }}} 
}}{{#nextdefine|..
}}...
```

If needs no-breakable line, you can use a `<span style="white-space: nowrap">`. It can be in separated template like {{nobr}}.

**Comment by TriMoon** [comment]
The reason for that kind of coding is because templates include newlines in their output if you don't do it this way :wink: 
it's like:
```html
<div>blabla</div>
<div>blabla</div>
```
versus:
```html
<div>blabla</div
><div>blabla</div>
```
For only text displayed you could use the nowrap, but when you generate html extra newlines get converted to ```<p></p>``` etc which mess up the generated html.

**Comment by TriMoon** [comment]
update: Seems the no host error above is caused by my own project config, where i used the object notation version instead of your current <kbd>mediawiker.</kbd> dot notation....I will try that part later...

**Comment by tosher** [comment]
It's an incorrect project file structure, needs:
```json
{
        "build_systems": [...],
        "folders": [...],
	"settings":
	{
             "mediawiker.site": {...}
        }
}
```

**Comment by tosher** [comment]
```
Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.sublime-syntax
```
Your ST's installation hasn't syntax for tsql. Not error - just message from ST.

```
Warning: Page has en unclosed element of type Div at position 7177, force closing at 7181..
Warning: Page has en unclosed element of type Div at position 8007, force closing at 8011..
```
Messages from the plugin's parser - object doesn't has a close-tag or it maybe a parsing error. It's ok for hard pages like yours :)
... and it can brake the popups.

**Comment by TriMoon** [comment]
> It's an incorrect project file structure, needs:
> 
> ```json
> {
>         "build_systems": [...],
>         "folders": [...],
> 	"settings":
> 	{
>              "mediawiker.site": {...}
>         }
> }

You are using the **settings** object-key of **sublime-text self**, the note makes it clear that the "settings" object-key is refering to sublime text **own** settings.
<kbd>Note that only settings in the category Editor Settings may be controlled by a project.</kbd>

Therefor you should use your own plugins name here instead of "settings" used in that example.
By doing so you separate your plugins settings from other plugins and sublime text self, plus you won't need your dot notation anymore either... example:
```json
{
	"build_systems": [...],
	"folders": [...],
	"settings": { settings for SublimeText },
	"syntax_override": { settings for project specific syntax plugin },
	"mediawiker":
	{
		"site": {...}
	}
}
```

> ```
> Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.sublime-syntax
> ```
> 
> Your ST's installation hasn't syntax for tsql. Not error - just message from ST.

But it comes from **MediawikiNG.sublime-syntax** and starts with _**Error** loading_
Maybe that's why the other errors...

**Comment by tosher** [comment]
Another no-brake way, without visually breaking tags:
```html
<div>blabla</div><!--
--><div>blabla</div>
```
Just empty comment.

**Comment by TriMoon** [comment]
> Another no-brake way, without visually breaking tags:
> 
> ```
> {{blabla}}{{blabla}}
> ```
> 
> Just empty comment.

The whole point of coding like i do is to **prevent** unwanted output from the template, you just make it output even more unwanted stuff if you do it like that. :wink: 
Maybe you should look into options to hand-over the syntax highlighting to other highlighters.
That will be better for your workload and highlighting issues with any languages people might be using.

Anyway thanks for your work so far, i have stopped editing wiki pages again for some time and moved over to other stuff, but i'm sure i will be needing this project again when i edit wiki's in futute :+1:
