### ISSUE TITLE
JS and CSS files

### ISSUE THREAD

**Issue by X1machinemaker1X** [tosher/Mediawiker#135]
If I open a file in the Mediawiki namespace, such as Mediawiki:Common.js, it opens with the plain text syntax. I would really prefer if JS and CSS files opened with their specific syntax. Maybe thats possible already. I see a couple settings mediawiker_syntax_css and mediawiker_syntax_js but I can't figure out what to set those to in order to get the syntax highlighting.

**Comment by tosher** [comment]
Please, check this settings in your configuration:
```json
    "mediawiker_syntax_lua": "Packages/Lua/Lua.sublime-syntax",
    "mediawiker_syntax_css": "Packages/CSS/CSS.sublime-syntax",
    "mediawiker_syntax_js": "Packages/JavaScript/JavaScript.sublime-syntax",
```

**Comment by tosher** [comment]
Yes, it's an error and will be fixed in next version.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.5.0

**Comment by X1machinemaker1X** [comment]
Looks to be working now. I downloaded the zip and extracted it to the packages directory. Idk how long it takes package control to see there's a new version.

**Comment by tosher** [comment]
I guess a few hours
