### ISSUE TITLE
Weird encoding issues in most recent changelog entry

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#136]
[Entry for 3.5.1](https://github.com/tosher/Mediawiker/blob/master/Changelog.mediawiki#mediawiker-351) has lots of literal entities.

**Comment by tosher** [comment]
Please, check it in Sublime. It's a mediawiki source and Github shows it with escaping html tags.

**Comment by tosher** [comment]
This changelog is not for Github, it's for showing in Sublime text. ST uses [minihtml](https://www.sublimetext.com/docs/3/minihtml.html) or just text :)

Changelog for Github - [Releases](https://github.com/tosher/Mediawiker/releases)

**Comment by reagle** [comment]
Okay. I find it a little annoying having to look at the changelog (I typically have to resort to using the mouse/pointer), but this is a minor issue.
