### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by X1machinemaker1X** [tosher/Mediawiker#137]
The default keybindings for OSX (for all really), should probably us "primary" instead of ctrl. primary is ctrl if on windows, cmd if on mac.

**Comment by tosher** [comment]
I'm not sure for all, but I will change some of them (Save, Italic, Bold, etc.)

**Comment by X1machinemaker1X** [comment]
sweet

**Comment by X1machinemaker1X** [comment]
also, another suggestion. The default "new" page comment that appears at the top of the page is always in the mw comment format  even when that page is a css, javascript, or json file. It'd probably be nice if the comment followed the language of whatever that file was

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Mediawiker/releases/tag/v3.5.2
