### ISSUE TITLE
Is it possible to use Color Highlighter with Mediawiker?

### ISSUE THREAD

**Issue by RheingoldRiver** [tosher/Mediawiker#139]
I'd like to have hex keys highlighted when I edit my wiki's CSS pages, but from what I can tell by default Color Highlighter package won't work because Mediawiker pages aren't saved locally. Is there any way I can get around this to get highlighting back?

**Comment by tosher** [comment]
https://packagecontrol.io/packages/Color%20Highlighter

FAQ
```
The plugin doesn't work in HTML/JS/VUE/OTHER files

Yes, it does. Highlighting colors is just disabled by default in all files but stylesheets. To enable highlighting colors in files with any extension you need to modify file_extensions setting and add the required extension there. You can also put "all" there and the plugin will be enabled for all files. If you have enabled some extensions before, they need to be reenabled due to the previous section.
```

```json
"file_extensions": ["all"]
```

**Comment by RheingoldRiver** [comment]
Ahh I was editing wiki CSS sheets so I thought that didn't apply in this case, but yeah setting it to all also removes the need to have anything locally saved. Thanks for the answer, this works now!
