### ISSUE TITLE
syntax highlighting with nested templates

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#140]
When I put the following in my mediawiki pages, the syntax highlighting becomes useless `{{peacock term|{{subst:DATE}}}}`. *Everything* afterwards is red.

**Comment by tosher** [comment]
Thanks! I'll check it

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Mediawiker/releases/tag/v3.5.3

**Comment by reagle** [comment]
Thanks!
