### ISSUE TITLE
regex on titles to determine initial page content & wiki farms

### ISSUE THREAD

**Issue by RheingoldRiver** [tosher/Mediawiker#143]
Hi! There are two features I would like, but I wanted to try implementing them myself, but I wanted to check with you before doing so if you'd be ok with the contribution & also with having them in general.

The first is, to add a setting that's a list of regular expressions & corresponding initial page texts. Right now I'm doing this explicitly but I wanted to change this do be done through settings file:

```
def get_new_text(page_name, namespace):
	if namespace == 828:
		if page_name.lower().endswith('/doc'):
			return '<includeonly>{{luadoc}}[[Category:Lua Modules]]</includeonly>'
		elif page_name.lower().endswith('/i18n'):
			return 'return {\n\t["en"] = {\n\t\t\n\t}\n}'
		elif page_name.endswith('Class'):
```

 The second thing was, I edit on Gamepedia and often want to open a page from a random wiki but don't necessarily need access to that wiki more than once. I'd like to set up the ability to configure an entire wiki farm login instead of a single wiki - opening a new wiki in this farm would behave similarly to opening a page, and you could set it to list the most recent N wikis from that farm alongside open-new-wiki list that you currently have. The farm would specify pattern matching on the URL with spaces separating inputs so you could do %s.domain.com/%s/ if needed.

So a settings file for this might look like:

```
farms: [
 {
  name: "Gamepedia",
  pattern: "%s.gamepedia.com",
  display_prefix: "GP - ",
  max_remembered: 10
 }
]
```

It would have a "current farm" similar to current wiki but that would only be used for the purposes of selecting the next pattern to pick from. The display prefix would be prepended to the name of the wiki in the all wikis menu.

I'm unsure if I would be able to implement the wikifarm functionality, and I'm unsure of timeline on either since I have a couple projects for work I need to finish but I wanted to check with you before starting if you'd be ok with these.

Thanks!

**Comment by tosher** [comment]
1. Maybe, will be better to use Jinja external template (in the `User` folder). In the plugin just render it, if exists, Need to think.

**Comment by tosher** [comment]
2. It's a good idea, but hard implementable with current code - many things are linked to fixed host settings (history, favorites, host connection, etc.).

Instead of this, i'll add a small option to host settings: `parent`, for example:

```json
"it.wikipedia.org": {
    "host": "it.wikipedia.orgt",
    "parent": "en.wikipedia.org"
}
```
With these settings italian wikipedia will be available with the same options as en.wikipedia.org, nothing else is needed.

And i'll add the new command `Add SSO-linked wiki` as a fast way to add child wiki site. This solution requires hand action, but it's simple and compatible with current code.

**Comment by tosher** [comment]
2. https://github.com/tosher/Mediawiker/releases/tag/v3.5.4

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.6.0

**Comment by RheingoldRiver** [comment]
Thanks!! This works perfectly! The only thing is, in your example, having the comment on its own line will result in a blank line before the template text on each new page, I had to comment out all my newlines. Here is my current template:


```
{%- if page_namespace == 828 -%}
	{%- if (page_name|lower).endswith('/doc') -%}{#
 ----------------------------------------- 
   -------- module documentation --------- 
 ----------------------------------------- 
#}<includeonly>{{ "{{luadoc}}" }}[[Category:Lua Modules]]</includeonly>
	{%- elif (page_name|lower).endswith('/i18n') -%}{#
 ----------------------------------------- 
         -------- i18n module --------- 
 ----------------------------------------- 
#}return {
	['en'] = {
		
	},
}
	{% else -%}{#
 ----------------------------------------- 
       -------- normal module --------- 
 ----------------------------------------- 
#}local util_args = require('Module:ArgsUtil')
local util_cargo = require("Module:CargoUtil")
local util_html = require("Module:HtmlUtil")
local util_map = require('Module:MapUtil')
local util_table = require("Module:TableUtil")
local util_text = require("Module:TextUtil")
local util_vars = require("Module:VarsUtil")
local i18n = require("Module:I18nUtil")
local lang = mw.getLanguage('en')
local h = {}
local p = {}
function p.main(frame)
	local args = util_args.merge(true)
	i18n.init('{{ page_name | replace('Module:', '') }}')
end
return p
	{% endif %}
{%- elif (page_name|lower).endswith('/js') -%}{#
 ----------------------------------------- 
          -------- js page --------- 
 ----------------------------------------- 
#}$(function() {
	
});
{% else -%}{#
	NOTE: default text 
#}{{ page_text }}
{% endif %}
```

**Comment by tosher** [comment]
It was just example :)
