### ISSUE TITLE
Can't use site selections anymore

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#144]
I pulled the 3.5.4 update this morning, but didn't change anything in my settings. Nonetheless, it broke my editing ability because sites are messed up.

- First, I was not able to successfully switch between sites. Even when I selected a site, and brought the panel up again, the caret would still show a different site. Also, the history/favorites belonged to a different site.
- I saw the changelog said something about a new way to specify sites via `parent`, so I took the new/default config and started with that. Now the plugin is giving errors.
- I then decided to simplify, and use only one site, without any parent declarations, and I'm getting the following errors:

```
reloading settings Packages/User/Mediawiker.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1034, in run_
    return self.run(**args)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_page_actions.py", line 16, in run
    if not utils.conman.require_password():
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 877, in require_password
    site = self.get_site(name)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 719, in get_site
    self.get_site_config(name=name)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_utils.py", line 655, in get_site_config
    site_config = props.get_site(name)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mwcommands/mw_properties.py", line 283, in get_site
    if site_settings.get('parent'):
AttributeError: 'NoneType' object has no attribute 'get'
reloading /Users/reagle/Library/Application Support/Sublime Text 3/Packages/User/Mediawiker.sublime-settings
```

**Comment by reagle** [comment]
I added another site, with a parent declaration, but I still get errors, and I can even open pages on the active site:

```
	"site":
	{
		"English wikipedia":
		{
			"authorization_type": "login",
			"cookies_browser": "chrome",
			"domain": "",
			"host": "en.wikipedia.org",
			"http_auth_login": "Reagle",
			"http_auth_password": "PASSWORD",
			"https": true,
			"is_ssl_cert_verify": true,
			"is_wikia": false,
			"oauth_access_secret": "",
			"oauth_access_token": "",
			"oauth_consumer_secret": "",
			"oauth_consumer_token": "",
			"pagepath": "/wiki/",
			"password": "PASSWORD",
			"path": "/w/",
			"preview_custom_head":
			[
			],
			"preview_sandbox": "",
			"proxy_host": "",
			"retry_timeout": 30,
			"show_red_links": false,
			"use_http_auth": false,
			"username": "Reagle"
		},
        "Meta": {
            "host": "meta.wikimedia.org",
            "parent": "en.wikipedia.org"
        }

	},
	"site_active": "English wikipedia",
```

**Comment by reagle** [comment]
I just remembered that when I updated the plugin (from "overwrite") there was a syntax error popup.

**Comment by reagle** [comment]
I downloaded mediawikier from github and checked out v3.5.3 . However, I can't get the manual install to work because it complains it can't import jinja2. I think it managed to install its other dependencies...

**Comment by reagle** [comment]
I deleted the git manual install, went to install from Package Control, and have the same jinja2 import error.

**Comment by tosher** [comment]
Hmm.. I can't to reproduce this problem.

P.S. All dependencies must be installed by Package Control.

**Comment by reagle** [comment]
Aren't dependencies pulled in automatically on the next restart of Sublime?

**Comment by tosher** [comment]
Please, try to rename site name to 'en.wikipedia.org' (from English wikipedia), maybe i made an error in site-get logic.

**Comment by tosher** [comment]
Package Control prints in the console messages about all installs of the dependencies.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.5.5

All fine in the plugin, but I set an incorrect values in default settings, child site must use of parent's site name, not host. In my "User settings" I have the same values for them and I made a typo in default settings.

**Comment by reagle** [comment]
On the dependencies, the plugin doesn't work because it's saying jinja2 isn't available.

```
Package Control: Installing 2 missing dependencies
Package Control: The dependency 'markupsafe' is not available
Package Control: The dependency 'python-jinja2' is not available
```

**Comment by tosher** [comment]
https://github.com/SublimeText/LaTeXTools/issues/1414

**Comment by reagle** [comment]
1. I couldn't manually install the dependencies for some reason...
1. reverted my ST3 folder to a week ago; yet, I was still have problems with mediawiker...
1. updated mediawiker to the latest, but it seemed to be choking on the config file from 3.5.3 -- is 3.5.4+ supposed to be backwards incompatible?
1. copied the new default config file, modified it, and now it seems to be working.
