### ISSUE TITLE
How do I disable the autocomplete of wiki links?

### ISSUE THREAD

**Issue by robertsky** [tosher/Mediawiker#146]
I am having an issue where when I what to link to another wiki article in the article I am editing, Sublime just freezes out a long time (long enough for me to switch out to read a manga chapter or two at least). During this time, I can't touch Sublime Text as it reflects as Not Responsive. If I did, the Windows system would recommend to end Sublime Text. Then, it displays the various links available in a dropdown menu.

![image](https://user-images.githubusercontent.com/1820367/64476851-9d0b3d00-d1c6-11e9-8188-a78a3ccc855e.png)
(This wiki link is what I am referring to.)

I do not need the dropdown menu as I would have done my searches beforehand. Any way to disable this action, or rectify the non-responsive period?

I am editing on the English Wikipedia. Also, it might be of interest to you that Sublime will lag out as well on Windows if you open a long list, such as this https://en.wikipedia.org/wiki/Index_of_Singapore-related_articles.

Let me know if you need any details, you will have to guide me on how to extract logs from Sublime Text though if you need them.

**Comment by tosher** [comment]
You can just increase the value of option `page_prefix_min_length` in settings (default: 3) - the number of characters after which the autocompletion is triggered.

**Comment by robertsky** [comment]
Thanks! that works!

**Comment by rabin-io** [comment]
Hi @tosher , this kinda thing should be copied to the wiki to allow others to find it more easily.
