### ISSUE TITLE
Reload all open pages option

### ISSUE THREAD

**Issue by RheingoldRiver** [tosher/Mediawiker#147]
Hi! Could you add a reload-all option? Maybe it could take a couple arguments as well so users can add extra custom command palette options:

* In current wiki / all pages on all wikis
* In current window / in all windows
* Only pages without unsaved changes / prompt on pages with unsaved changes / discard all unsaved changes and reload

My specific use case for this right now is I typically keep about 20 utility modules open so I can refer to the functions they have, and I recently ran a find-replace on all my modules to rename one module to another, so now every time I make a change I end up having to reload the page. I guess restarting Sublime is an option but if it's not too much trouble to add, it would be a lot more convenient to have this as an option, especially if I have unsaved changes that I don't want to lose in other documents. Thanks!

**Comment by tosher** [comment]
As beta version:

https://github.com/tosher/Mediawiker/releases/tag/v3.5.7
