### ISSUE TITLE
Support for folding headers 

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#148]
Hi, 

I think I had this option working in the past, but the new syntax highlighting is not supporting header folding.

**Comment by tosher** [comment]
Do you have an example of unworking text? I checked on some wikipedia's pages and it works for me.

**Comment by rabin-io** [comment]
The folding option is not consistent, as you can see in the first picture, I don't have any folding options,

![2019-11-22_09-59](https://user-images.githubusercontent.com/5116363/69408224-0a7f3200-0d0f-11ea-9cb5-d1848b0fe8b6.png)

But in another page I have folding option in some headers, but all of them

![image](https://user-images.githubusercontent.com/5116363/69408475-a3ae4880-0d0f-11ea-8e4c-a397dc780eb0.png)

And the current syntax is `Mediawiki NG`

**Comment by tosher** [comment]
Thanks, I will check it. 

If you trying to call the Fold/Unfold commands from Command pallete, does it works? (when no options exists)

**Comment by rabin-io** [comment]
Hmm, from the menu when I try `Fold All` it only fold the elements which show the gutter.
when my carret is over the `==` part of the header using the menu, noting happen, but the keyboard shortcrust  works, and then I see the `Unfold` gutter.

![image](https://user-images.githubusercontent.com/5116363/69424999-ac644600-0d32-11ea-85a7-c17ebca6cb3e.png)

Clicking on it will unfold the section, and the gutter disappeared.

**Comment by tosher** [comment]
Thanks for the information, will research it..

**Comment by tosher** [comment]
The plugin/syntax don't make fold blocks in native way, for folding and hover functions uses a special parser. The plugin don't do anything to show Fold gutter, but Unfold gutter is shown by ST natively, based on already folded block of text.

The plugin only draws gutters on the left-left side like `h1`, `h2`, etc.. to show possibility for folding.

For folding you can use hover menu, shortcuts or palette commands.

Maybe you have some another plugins like Syntax​Fold?

> I found one bug in folding levels, it will be fixed soon.

**Comment by rabin-io** [comment]
I don't have this specific plugin, here is my installed packages list

```
A File Icon
AdvancedNewFile
AlignTab
Ansible
AnsibleSnippets
ApacheConf
ApplySyntax
Bind Zone files
Boxy Theme
Dockerfile Syntax Highlighting
EditorConfig
Expand Selection to Quotes
INI
Jinja2
Junos
nginx
Package Control
PHP Companion
PHP CS Fixer
ProjectManager
RPM Spec Syntax
SnippetMaker
SublimeLinter
SublimeLinter-contrib-ansible-lint
SublimeLinter-phpcs
SummitLinter
Terrafmt
Terraform
TerraformSnippets-AWS
```
