### ISSUE TITLE
Don't show console panel unless there are errors

### ISSUE THREAD

**Issue by LunarTwilight** [tosher/Mediawiker#149]
Could it please be made so that instead of showing the console panel after every action that the console panel only shows up if theres an error?

**Comment by tosher** [comment]
Done, testing..

**Comment by tosher** [comment]
Please, check the new version:

https://github.com/tosher/Mediawiker/releases/tag/v3.5.6

**Comment by LunarTwilight** [comment]
and it works, thanks!
