### ISSUE TITLE
"search_namespaces" in individual site setting

### ISSUE THREAD

**Issue by BryghtShadow** [tosher/Mediawiker#151]
I'd like have the option to set `"search_namespaces"` for individual wikis.
For example, a wiki I edit has 912 files with the same prefix (`File:Game,C`), and this causes ST3 to be unresponsive for a while after typing `'[[File:Game,C` (sometimes, I have to kill `plugin_host.exe` and then restart ST3). On a smaller site, I may wish to have other namespaces to search.
I think this option should alleviate unresponsive ST3 for specific wikis.

**Comment by tosher** [comment]
Please, try the new version:

https://github.com/tosher/Mediawiker/releases/tag/v3.5.9

**Comment by BryghtShadow** [comment]
The override is working when the string isn't empty, which is good. 👍

Empty string will default to global settings; would it be possible to only inherit from global if the parameter is not present in site? (Wasn't sure of if it's possible to completely disable searching, and that might be for a separate ticket)

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.6.0
