### ISSUE TITLE
Changelog unviewable

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#156]
When I got the notification for the 3.6.0 update, I tried to view the changelog.

1. Clicking `view in browser` does nothing; no browser is launched.
2. The native ST changelog view is weird. The left side is cut off and I can't move the view so as to see it.

<img width="1022" alt="Screen Shot 2020-03-17 at 9 57 53 AM" src="https://user-images.githubusercontent.com/596814/76863587-151d8400-6836-11ea-83ce-311440d61354.png">

**Comment by tosher** [comment]
1. Will be fixed (MacOS specific)
2. Try to turn on Word Wrap

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.6.1

**Comment by reagle** [comment]
Thanks!
