### ISSUE TITLE
Add jinja template file to preferences

### ISSUE THREAD

**Issue by RheingoldRiver** [tosher/Mediawiker#157]
Can you add a link from preferences -> Mediawiker that says "Open new page template" ? If you click it and don't have one configured, it would alert that with a note saying "Please set this via `new_page_template_path`", otherwise it opens that location in your current window.

I'm happy to try coding this myself but it seems maybe complicated enough I don't want to risk giving you extra work by attempting.

Thanks!

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.6.1

**Comment by RheingoldRiver** [comment]
thank you!! this is perfect!
