### ISSUE TITLE
[Bug] Link suggestion adds onto what was already typed

### ISSUE THREAD

**Issue by moose-again** [tosher/Mediawiker#167]
Hi, when typing in a link and clicking one of the dropdown suggestions, it adds to what has already been typed and causes words to be repeated. 
### Steps to reproduce
- Open double square brackets
- Start typing in a page name. example: `[[Big Buc`...
- Click one of the link suggestions example: Big Buck Bunny
### Expected behavior
I should get `[[Big Buck Bunny]]`
### Actual behavior
I get `[[Big Big Buck Bunny]]`

**Comment by tosher** [comment]
Thanks, I will check it.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.6.4

**Comment by moose-again** [comment]
Sorry to bother you again, but something's still off. Now it happens like...

- I open double brackets
- I type in `[[Big Buc`
- I click the link suggestion `Big Buck Bunny`
- Text comes out: `[[Big ck Bunny]]`

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/v3.6.5

Second try :)
