### ISSUE TITLE
Edit summaries in the console 

### ISSUE THREAD

**Issue by RheingoldRiver** [tosher/Mediawiker#180]
Hi, is #176 ok? I've been using this branch for the past few weeks and finding the summaries really helpful to see where I am, but it could also be gated behind a setting.

example:
![image](https://user-images.githubusercontent.com/18037011/119637842-b198ca00-bddb-11eb-9f6b-67968d2e5a13.png)

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/pull/176#pullrequestreview-670086991

**Comment by RheingoldRiver** [comment]
kk I updated (see comment there though about Python version & fstrings)

**Comment by tosher** [comment]
Done! Thank you! ^)
