### ISSUE TITLE
Automatically converting tabs to spaces/spaces to tabs on load

### ISSUE THREAD

**Issue by gigamicro** [tosher/Mediawiker#183]
The plugin should properly autodetect indents in lua modules (and css), according to the `detect_indentation` Sublime setting

**Comment by tosher** [comment]
Thanks, will check it

**Comment by tosher** [comment]
Please, could you describe the use-case when it not works (settings, tabs/spaces in file)?

**Comment by gigamicro** [comment]
```JSON
{
	"translate_tabs_to_spaces": true,
	"detect_indentation": true,
}
```
```lua
local p = {}
function p.doThing()
	return 42
end
return p
```

**Comment by tosher** [comment]
I don't know how to make it fully correct, in new version just added new option to prevent tabs translation in page's text:

https://github.com/tosher/Mediawiker/releases/tag/v3.6.11

**Comment by gigamicro** [comment]
would you mind merging that branch?

**Comment by tosher** [comment]
Done! :)
