### ISSUE TITLE
syntax highlighter doesn't recognize <math> tags with "display=..." attributes

### ISSUE THREAD

**Issue by scottbb** [tosher/Mediawiker#189]
The Wikipedia `<math>` tag allows for `display=block` and `display=inline` attributes. However, the syntax highlighter in this extension doesn't recognize those attributes.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Mediawiker/releases/tag/v3.6.13

**Comment by scottbb** [comment]
Works as expected. Great job!
