### ISSUE TITLE
12 months of inactivity of repository owner

### ISSUE THREAD

**Issue by jandahl** [tosher/Mediawiker#196]
I'm sorry to say we might have lost @tosher 

Thanks for everything man, you really made my life easier. Hope you've just decided to go luddite.

**Comment by tosher** [comment]
I'm here, but at the moment I don't have any new ideas to enhancement :)

Thank you for your support!

**Comment by jandahl** [comment]
<3 

I've actually been checking your "GitHub activity" graph every few months now. Glad to hear it wasn't a slow and painful death that caused inactivity. Take care :-)
