### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] on wiki connection

### ISSUE THREAD

**Issue by L32GIT** [tosher/Mediawiker#198]
Hello, not sure if it's a proper place to ask, but

Fresh installed Sublime 4, fresh installed Package control and then Mediawiker through it.
Sublime is open under admin rights. Windows 10.

I've set up settings and credentials for the wiki I would tike to edit, but upon opening any page it says:
`Connecting to "https://wiki.captain-of-industry.com" ..   >>>  failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548) Unable to get page "Brickworks", ConnectionFailed exception raised: No valid connection available`
  
  In my config file I've properly set:
  `"site_active": "COI wikipedia"`
  
  and
  `"COI wikipedia": {
            // Authorization type: "login" / "oauth" / "cookies"
            "authorization_type": "login",
            // Site url
            "host": "wiki.captain-of-industry.com",
            // API path (https://en.wikipedia.org/wiki/Special:Version)
            "path": "/",
            // Pages path (https://en.wikipedia.org/wiki/Special:Version)
            "pagepath": "/",
            // Login authorization type
            "username": "L32",
            // Login authorization type
            "password": "MyPass",
            // Domain for corp. wikies with LDAP authorization
            "domain": "",
            // Using HTTPS protocol instead of HTTP
            "https": true,
            // Verify server SSL certificates on connection
            "is_ssl_cert_verify": true,
            // Connection through proxy server: like http[s]://[login:password@]domain.com[:3128]
            "proxy_host": "",
            // Additional HTTP authorization: Basic or Digest
            "use_http_auth": false,
            // Additional HTTP authorization: Basic or Digest
            "http_auth_login": "L32",
            // Additional HTTP authorization: Basic or Digest
            "http_auth_password": "MyPass",`
            
  What logs should I provide, where should I search for help on this? Should I contact wiki admins? Or is this a problem with my own PC?

**Comment by L32GIT** [comment]
Just checked that connection to the English Wiki without authorization works fine. At least it reads the page.

**Comment by tosher** [comment]
You copuld try: `https: false` or `is_ssl_cert_verify: false`
