### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [tosher/Mediawiker#32]
I would like to use your grammar for Mediawiki but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/blob/master/license.md

**Comment by tosher** [comment]
Original tmLanguage:
https://github.com/textmate/mediawiki.tmbundle

**Comment by pchaigno** [comment]
> https://github.com/tosher/Mediawiker/blob/master/license.md

Oops missed that! Thank you for pointing it out!

**Comment by scholer** [comment]
I agree, tosher. The original license allows you to modify and re-license
it however you'd like. And your  repository is clearly distributed under
the license in the root directory (MIT license, if I recall correctly?).

In other words, this issue can be closed, in my opinion.

And thanks for your work with Mediawiker, by the way! :)

Cheers,
  Rasmus

**Comment by tosher** [comment]
Thanks for your support! :)
