### ISSUE TITLE
Feature request: Option to disable publish page command

### ISSUE THREAD

**Issue by moroboshi** [tosher/Mediawiker#35]
I would like to have a configuration option to disable the publish page command: I'm not comfortable with the possibility to upload article  with a single keystroke because I translate/write long articles and make extensive change to existing one so I prefer to check the preview several time before uploading the final version.

An alternative could be to add a confirmation step before  publishing the article and enabling/disabling the confirmation step in the plug-in configuration, with a default of disable so there would be no change in the default behaviour of the plug-in.

**Comment by jandahl** [comment]
If you leave the default setting, `"mediawiker_skip_summary": false,`, ST will ask you for a comment before publishing.

**Comment by tosher** [comment]
..and `false` is the default value.
..and with option `mediawiker_wiki_instead_editor: false` we have disabled publishing page to wiki by <kbd>ctrl+s</kbd>.

**Comment by moroboshi** [comment]
ok thanks!
