### ISSUE TITLE
Feature request: Command to translate internal wikilink using interwiki and wikidata

### ISSUE THREAD

**Issue by moroboshi** [tosher/Mediawiker#36]
Normally I translate (or add content) translating articles from en.wiki to it.wiki, so I have to traslate wikilink from the en.wiki title to the it.wiki title.

I would like to have an option to configure a "target wiki" and a command to  search the current select text as title article on the target wiki and get the corresponding title on the working wiki using the wikidata database. For example select the text “**Steve Jackson (US game designer)**" search it as article title on en.wiki (target wiki) and getting "**Steve Jackson (1953)**" on it.wiki (working wiki)

**Comment by scholer** [comment]
Wow, this sounds very use-case specific. Are you sure it would not be
easier to use another strategy, e.g. first transport the pages from one
wiki to the other in a batch script (which would transform links, etc). The
batch script could output the target page names. Then you could open the
transformed pages on the working wiki in Mediawiker and do all the human
work of translating from English to Italian. At least that's how I would do
it. :)
/Rasmus

**Comment by tosher** [comment]
Not fully, but i think, will be possible to add:
* In search box, use selected text by default, like **mediawiker_clipboard_as_defaultpagename** option
* Use API query to get another languages versions of opened page urls (show as menu to open selected page), for example:
** http://en.wikipedia.org/w/api.php?action=query&prop=langlinks&titles=Steve%20Jackson%20%28US%20game%20designer%29

Is it will be usefull?

**Comment by moroboshi** [comment]
@scholer, I prefer to check every wiki one by one, the correspondence between article on different language wiki is not always perfect and I could miss wikilink not translated because of missing article on the source or target wiki.
@tosher not fully but would be useful - thanks for considering my request!  - the only inconvenience is that I have to keep en.wiki as active wiki and so auto completion of internal wiki would work on en.wiki not on it.wiki

**Comment by tosher** [comment]
Please, try the new version (2.5.0):

Mediawiker 2.5.0:
* Multi-site support - own wiki site per Sublime text's view (tab). Now, **mediawiki_site_active** setting is used as default site for new views. But, on opening a page from existing view it's own settings will be inherited.
* New command to show other languages versions of the current page: **Show language links**. On opening page with selected language, active site will be automatically switched to the respective language version site. For example, from english page on en.wikipedia.org we want to open italian version of this page - active site will be switched to it.wikipedia.org for italian version view.

Note 1: This version supports the possibility to switch between the language versions only for the sites using domain name scheme like *lang_prefix*.site.com, e.g. en.wikipedia.org. Other schemes can be added in future.
Note 2: Selected language version site settings must be in preferences for work with it's pages.

**Comment by moroboshi** [comment]
It's useful, but not what I need. This function load a language version of the current page in another language, but what I would like is a function to check if the current  selected text is the title of an existing wiki on wiki and replace it (only the selected text) with the title of the corresponding article on a wiki in another language.

**Comment by tosher** [comment]
Mediawiker 2.5.1:
* With selected text, **Show language links** tries to show language links for it.
* Selected language link can be opened as page or it's name can be used as replacement for currently selected text (first region only in multiselect mode).

**Comment by moroboshi** [comment]
working thanks.
