### ISSUE TITLE
Color Schemes

### ISSUE THREAD

**Issue by DrLulz** [tosher/Mediawiker#38]
I've made two color schemes. Would like some feedback to make them better.

[Railscast](https://gist.github.com/DrLulz/9ed6f9a21cd88ea3e322/raw/54ec5cb73d75bb1a6eea96820829140c94cdcf59/MediaWiki-DrLulz-Railscast.tmtheme), [Tomorrow Night-ish](https://gist.githubusercontent.com/DrLulz/9ed6f9a21cd88ea3e322/raw/69694e29fbb596fbfa91c6a3da7adaf7d33b2168/MediaWiki-DrLulz-Twilight.tmtheme)
  
[Download](https://gist.github.com/DrLulz/9ed6f9a21cd88ea3e322)

**Comment by tosher** [comment]
Ohh, why me? :) Colors - it very personal moment :)
I think, you can publish your themes as sublime packages, like:
* https://github.com/ant7/ant-sublime-theme
If it can be used with mediawiki syntax - it can be used for other markup languages (markdown, etc.).
With your own repository you can get feedback from many users, not one :)
