### ISSUE TITLE
Sublime asks me to save after pushing an updated article.

### ISSUE THREAD

**Issue by Plloi** [tosher/Mediawiker#39]
To me a pushing an article is a "save operation".
Maybe add on option to open wiki pages as scratch pads to keep Sublime from asking me to save  an already "saved" file.

**Comment by tosher** [comment]
Good idea, thanks! Will be in next version.

**Comment by tosher** [comment]
Please, try the new version (2.5.2)

**Comment by Plloi** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "C:\Users\{user}\AppData\Roaming\Sublime Text 3\Packages\Mediawiker\mediawiker.py", line 179, in run
    sitecon = mw.get_connect(password)
AttributeError: 'module' object has no attribute 'get_connect'

**Comment by tosher** [comment]
After restarting Sublime Text problem exists?

**Comment by Plloi** [comment]
Restarting sublime cleared it up, not loading as scratch though.

**Comment by tosher** [comment]
After opening page from wiki, it showed as changed file (tab)?
And the same after publishing?

**Comment by Plloi** [comment]
On open it shows dirty, On save clean.

Looked like MediawikerLoad.on_modified is being called after load and setting dirty

**Comment by tosher** [comment]
It's on ST3 or ST2?
And how you open page?
Do you use **Mediawiki.tmLanguage** syntax highlighting file?

**Comment by Plloi** [comment]
ST3
Opened both from within ST and custom protocol link
Yes, I am using the  Mediawiki.tmLanguage

**Comment by Plloi** [comment]
Just tried ST2 everything seems fine there, so 3 only.

**Comment by tosher** [comment]
ST3 dev channel or not?

**Comment by Plloi** [comment]
ST3 Build 3083

**Comment by tosher** [comment]
I can't to reproduce this. Maybe it's a conflict with other plugin, which also fires on_modified event and set scratch to false..

**Comment by Plloi** [comment]
Found the offending plugin, was a project i was working on that triggered scratch false based on text, which my test page contain.
Works great now.

Sorry for the extra headache on that one.

**Comment by tosher** [comment]
No problem, glad that the issue is solved :)
