### ISSUE TITLE
Control-S keyboard shortcut mapped to Change Summary

### ISSUE THREAD

**Issue by gene1wood** [tosher/Mediawiker#41]
This may be obvious (I'm not that skilled at Sublime Text) but is there a way to reclaim the Control-S keyboard shortcut which Mediawiker takes over for the "Change Summary" function, so it can be reverted to the built in Sublime Text "Save" function?

I can't seem to break myself of the unconscious habit of saving with Control-S which ends up not actually saving the file.

**Comment by tosher** [comment]
User settings:
"mediawiker_wiki_instead_editor": false

**Comment by gene1wood** [comment]
Thanks! And what impact beyond [disabling the Control-S override](https://github.com/tosher/Mediawiker/blob/ac892217d2452622cf47bc51bb687195c962782a/Default%20%28Linux%29.sublime-keymap#L36) will this have, any?

**Comment by gene1wood** [comment]
And for anyone looking where to set these user settings, [the docs](https://github.com/tosher/Mediawiker#documentation) say "Preferences / Package settings / Mediawiker / "Settings - Default" and "Settings - User""

and you want to create text that says

```
{
    "mediawiker_wiki_instead_editor": false
}
```

**Comment by tosher** [comment]
This option was made specially for this shortcut :)

**Comment by gene1wood** [comment]
Cool thanks, I couldn't tell from the name that it related to the Change Summary or Save functions.

**Comment by tosher** [comment]
Yes, the name is not perfect, but too late to change it.
P.S. Command for this shortcut is not just *Change summary* action, it saves data to wiki server (**Post page**).
