### ISSUE TITLE
Unable to use search in Sublime Text 3

### ISSUE THREAD

**Issue by muloka** [tosher/Mediawiker#43]
When using Mediawiker:Search I get the following error:

    Traceback (most recent call last):
      File "/Users/muloka/Library/Application Support/Sublime Text 3/Packages/Mediawiker/mediawiker.py", line 849, in show_results
        for i in range(self.search_limit):
    TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by TicClickie** [comment]
Sounds like your Mediawiker configuration file is missing a `mediawiker_search_results_count` option, no?

**Comment by muloka** [comment]
Ah it's possible. I wasn't able to infer that from the GitHub wiki pages.

**Comment by tosher** [comment]
All settings has default values in **Settings - Default**, check it in 
```
Preferences/Package Settings/Mediawiker/Settings - Default
```

**Comment by muloka** [comment]
Thanks again.

**Comment by muloka** [comment]
@TicClickie @tosher thanks again!
