### ISSUE TITLE
Can I add a wiki site like community.wikia.com?

### ISSUE THREAD

**Issue by Jazzis18** [tosher/Mediawiker#47]
I can't get the pages from wiki sites such as community.wikia.com. This is due to the fact that you can only use wikipedia.org and mediawiki.org hosts or due to incorrect setup?

**Comment by tosher** [comment]
Must works on any site based on mediawiki core with enabled API.
I'll try to check work with community.wikia.com.

**Comment by tosher** [comment]
* http://api.wikia.com/wiki/Legacy_API
* API URL: http://api.wikia.com/api.php (not http://api.wikia.com/w/api.php)

**Comment by Jazzis18** [comment]
Okay, I'll try.
