### ISSUE TITLE
remember open page on post

### ISSUE THREAD

**Issue by alins** [tosher/Mediawiker#48]
would it be possible to remember the name of the page opened so on post i don't have to always type in the page? this would be a huge time saver

**Comment by scholer** [comment]
I don't think I've ever had to manually type the page name on post. Can you explain your use-case in detail? Usually you would open up a page, make some edits, then post the updated page. In this case, the page name should be remembered. Is this when you've created a new page from scratch?
Thanks,

**Comment by alins** [comment]
sorry, my bad, never mind. for some weird reasons i miss read 'changes summary', i thought that's where i need to alway input the page name. should have double checked the behaviour before wasting your time.
