### ISSUE TITLE
check page version on post

### ISSUE THREAD

**Issue by alins** [tosher/Mediawiker#49]
on post, right now the plugin is uploading the full page which in a highly collaborative environment could results in overwriting other people changes.

i wonder if is possible to change the behaviour a bit, maybe store locally the page version on open (or reopen), than on post first check the version. if the version differs either show a dialog box asking the user to choose what they want (overwrite|stop|) or open the new version in a different doc in sublime so i can run a diff and resolve the changes. if i where to have an option i would choose the second option (maybe have a setting that enables opening the new version automatically in a new doc by default)

what do you think? too complicated?

**Comment by scholer** [comment]
IMO, this is a good idea. I think the original mwclient library might have support for this, but even if it doesn't, it should be possible to implement in Mediawiker.

**Comment by alins** [comment]
that's awesome! i would loove to have something like this.

**Comment by tosher** [comment]
It seems like request for mediawiki engine - **Merge request** :) 
Will think..

**Comment by tosher** [comment]
Please, try the new 2.5.7 version.

**Comment by alins** [comment]
very nice, works perfectly. thank you so much

**Comment by alins** [comment]
hmm, i think we have a small problem. 

i open the page than i add small text in sublime and some other text directly in wiki. when i post the page from sublime is showing that dialog..perfect.

now i reopen the page, make another change just in sublime. when i post the dialog shows up again which it shouldn't since i reloaded the page right?

**Comment by tosher** [comment]
After reopen i can't to reproduce the problem, but when select **Ok** in dialog and then try to save once more, we have dialog - again.. I'll fix it..

**Comment by tosher** [comment]
Fixed.

**Comment by alins** [comment]
yap, is working properly now. thank you

**Comment by tosher** [comment]
Thanks for your interest to plugin!
