### ISSUE TITLE
Mediawiker is laggy when typing links to namespace pages on Wikia

### ISSUE THREAD

**Issue by absay** [tosher/Mediawiker#51]
For instance, if I try to write something like  `[[File:SomeFile.jpg]]` or `[[Category:SomeCategory]]`, the cursor will pause almost at every character, sometimes freezing the editor for a couple of seconds, and I get no auto-complete suggestions (though I'm not sure if I should), unlike regular content pages which have no issues at all. This happens with a wiki from Wikia.

Currently using latest Mediawiker release and Sublime Text 3.

**Comment by tosher** [comment]
Thanks, i will check what's wrong with categories, files and other non-page namespaces..

**Comment by tosher** [comment]
Fixed and optimized in [mw_0.8.0](https://github.com/tosher/Mediawiker/tree/mw_0.8.0) branch (based on new version of [mwclient](https://github.com/mwclient/mwclient)).
After tests it will be pulled into main version.

**Comment by tosher** [comment]
P.S. For completions of namespaces like Images, Categories you can add namespace numbers into option in the settings:
```json
"mediawiker_search_namespaces": "0,6,14"
```
* 6 - images
* 14 - categories

**Comment by tosher** [comment]
Please check the new version (3.0.0)

P.S. On big wikies completion list can be very large. For performance reasons you can increase the value of option in the settings:
```json
"mediawiker_page_prefix_min_length": 3,
```
Autocompletion fires when typed string has this length.

**Comment by absay** [comment]
Many thanks, Tosher. It seems to be working fine right now. A quick question: is there any setting to make typing a template name like `{{SomeTemplate}}` show autocompletion suggestions as well? I already added `10` to `mediawiker_search_namespaces` to no avail but I'm not sure if that's even possible at all.

**Comment by tosher** [comment]
Now, autocomplete works only in internal links (<code>[[]]</code>). 
To insert template we have an option **Insert template** - it will show templates list by prefix and the will add template with parameters on page.

**Comment by absay** [comment]
Alright, that is really cool. It would be great if it worked with the [portable infoboxes](http://community.wikia.com/wiki/Help:Infobox) as well but I think I would be asking too much and I'm not sure if it's worth the effort.

Many thanks for the plugin and for all the help, tosher!

**Comment by tosher** [comment]
As i see it's the same templates as classic mediawiki engine templates, but with different syntax in template's source. 
Are you ask about template's source editing or about inserting infobox into page?

**Comment by absay** [comment]
About inserting the infobox in a page. But I feel I need to be a bit more specific:

As it is now, inserting a template will grab any `{{{parameter|default value}}}`. This is extremely useful with normal templates, which covers like 90% of cases. But Wikia's portable infoboxes generate fields through the `<data>`, `<title>` and `<image>` tags, with the `source="parameter"` attribute, although regular `{{{parameters}}}` are allowed for custom formatting.

So, I can have a portable infobox called "My infobox" like this:

    <infobox>
    <title source="title" />
    <image source="file" />
    <data source="param1"><label>Param 1</label></data>
    <data source="param2"><label>Param 2</label><format>{{{param2|foo}}}</format>
    <data source="param3"><label>Param 3</label><format>{{{param3|}}}</format>
    </infobox>

And when I insert it, it will generate the next code:

    {{My infobox|param2=foo
    |param3=
    }}

thus getting only the `{{{ }}}` parameters.

Again, it would be cool to be able to get all the fields of a portable infobox, but to be honest, even though I find myself coding and using this kind of templates fairly often, it might not be the case for other wikis on Wikia, so I'm not sure if it's worth the effort or if it would be an easy task to integrate it into the current version.

**Comment by tosher** [comment]
Thanks for detailes! I will research this.

**Comment by tosher** [comment]
Please upgrade the plugin. Infobox support was added as a beta.
Some moments:
* For support on selected site, option **is_wikia** is required:
```json
		"Wikia":
		{
			"domain": "",
			"host": "bookshub.wikia.com",
			"https": true,
			"is_wikia": true,
			"pagepath": "/wiki/",
			"password": "Password",
			"path": "/",
			"username": "Username"
		},
```
* Default param value processed from **default** markup tag only.

If **is_wikia** param was set to **true** template inserting has two steps:
1. Trying to process infobox markup template
2. If parameters list is empty - processing in a standard way
