### ISSUE TITLE
Parse error when "proxy_host" is set.

### ISSUE THREAD

**Issue by nicolaevladescu** [tosher/Mediawiker#55]
Hello.

I have been trying to set up the plugin to use a proxy server via the "proxy_host" setting that appears to support only host and port (according to the documentation), i tried to specify the username and password via URL (user:password@host:port) and i get the parse error below via a sublime message window.

At a second look, i get the same error with the standard documented URL format of "host:port" also.

```bash
Connection failed for ('https', 'user:pass@proxy-01:3128'): Failed to parse: proxy-01:3128https:
```

I am using Sublime Text 3083 and the plugin is version 3.0.2 installed via Package Control 3.1.2

Thank you!

**Comment by tosher** [comment]
Thanks, i'll check it.

**Comment by nicolaevladescu** [comment]
No problem. Let me know if you need more info.

**Comment by tosher** [comment]
Please, try the new version (3.0.3).
P.S. Restart required after upgrade.

**Comment by nicolaevladescu** [comment]
Hello.

Proxy works now, i get a "Proxy Authentication Required" message.
But i still can't set a username and password for it.

Thank you, good work!

**Comment by tosher** [comment]
Must be:

```
To use HTTP Basic Auth with your proxy, use the http://user:password@host/ syntax...
```
http://docs.python-requests.org/en/latest/user/advanced/#proxies

It's a public proxy or not?

**Comment by nicolaevladescu** [comment]
It's not public, i tried the following syntax:
```bash
http://user:pass@proxy-host:port
https://user:pass@proxy-host:port
user:pass@proxy-host:port
```

I always get the same error: https://www.dropbox.com/s/j768b5tpwmk2tbl/Screenshot%202016-01-11%2016.38.18.png?dl=0

**Comment by tosher** [comment]
With test wingate proxy, works with:
```json
"https": true,
"proxy_host": "http://tosher:tosh123@192.168.100.3:8080"
```
and with incorrect password:
```
Connection failed for ('https', 'en.wikipedia.org'): 
HTTPSConnectionPool(host='en.wikipedia.org', port=443): 
Max retries exceeded with url: /w/api.php 
(Caused by ProxyError('Cannot connect to proxy.', 
OSError('Tunnel connection failed: 407 Proxy authorization required',)))
```

**Comment by tosher** [comment]
But, it's settings for [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication).
Which type is used on your proxy?

**Comment by nicolaevladescu** [comment]
It is also HTTP Basic Auth, but i have a bit longer and tricky password including some characters that need escaping like $ or @.

I will give it a try tomorrow with a test user and a simple password, then come back to you.

Thanks!

**Comment by tosher** [comment]
http://stackoverflow.com/questions/6172719/escape-character-in-git-proxy-password

**Comment by nicolaevladescu** [comment]
Hello.

I manually escaped reserved characters and it worked.

Thanks a lot!
