### ISSUE TITLE
Preview changes without saving while editing Wikipedia and other wiki-sites

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#62]
Whether it is possible to make somehow a fast preview the page of the wiki-site with the changes made by me without saving of the page? Thanks.

**Comment by tosher** [comment]
Very very restricted preview is possible - it will be local generated page, not preview on wiki site.
I'll commit the changes soon..

**Comment by tosher** [comment]
Please, try the new `3.0.8` version.

**Comment by Kristinita** [comment]
Great work!

Whether it is possible to make that when updatings a plugin the lines `"mediawiki_site"` weren't removed?

<pre>
"mediawiki_site":
    {
        "English wikipedia": { "host": "en.wikipedia.org", "path": "/w/", "pagepath": "/wiki/", "username": "", "password": "", "domain": "" },
        "Russian wikipedia": { "host": "ru.wikipedia.org", "path": "/w/", "pagepath": "/wiki/", "username": "", "password": "", "domain": "" },
        "Mediawiki": { "host": "www.mediawiki.org", "path": "/w/", "pagepath": "/wiki/", "username": "", "password": "", "domain": "" },
        "Циклопедия": { "host": "cyclowiki.org", "path": "/w/", "pagepath": "/wiki/", "username": "Саша_Черных", "password": "MyPassword", "domain": "" },
    },
</pre>

I had to re-enter the line of those sites with which I work. Thanks.

**Comment by tosher** [comment]
Already - all user setting must be defined in **Preferences/Package Settings/Mediawiker/Settings - User** - it's standard sublime's rule (default settings|user settings).

* https://github.com/tosher/Mediawiker/wiki/Howto

**Comment by Kristinita** [comment]
Thanks, I asked a stupid question.

Is it possible to carry out a preview in a **one** tab? Now each preview opens in a new tab, in the browser many tabs can be open.

**Comment by reagle** [comment]
I'm not sure how this feature works, so I went to try it and got this error:

```
Error loading scope:text.html: Unable to find syntax file for scope text.html in Packages/Mediawiker/MediawikiNG.tmLanguage
Error loading scope:source.ini: Unable to find syntax file for scope source.ini in Packages/Mediawiker/MediawikiNG.tmLanguage
Error loading scope:source.actionscript: Unable to find syntax file for scope source.actionscript in Packages/Mediawiker/MediawikiNG.tmLanguage
Error loading scope:source.latex: Unable to find syntax file for scope source.latex in Packages/Mediawiker/MediawikiNG.tmLanguage
Error loading scope:source.tsql: Unable to find syntax file for scope source.tsql in Packages/Mediawiker/MediawikiNG.tmLanguage
Error loading scope:source.postscript: Unable to find syntax file for scope source.postscript in Packages/Mediawiker/MediawikiNG.tmLanguage
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/home/reagle/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 1371, in run
    html = sitecon.parse(text=text, title=mw.get_title(), disableeditsection=True).get('text', {}).get('*', '')
TypeError: parse() got an unexpected keyword argument 'disableeditsection'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/home/reagle/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 1371, in run
    html = sitecon.parse(text=text, title=mw.get_title(), disableeditsection=True).get('text', {}).get('*', '')
TypeError: parse() got an unexpected keyword argument 'disableeditsection'
```

**Comment by tosher** [comment]
@reagle, just restart the sublime text.. internal mwclient library was updated and require restart of ST

**Comment by tosher** [comment]
@Kristinita, nope, unfortunately Sublime Text can't to control browser window - it's just system call to open url in default browser...

<kbd>Ctrl</kbd>+<kbd>w</kbd> - for fast closing of tabs :)

**Comment by reagle** [comment]
@tosher, confirmed. Is it odd that the preview command is in sublime's palette and not the mediawikier specific one?

**Comment by tosher** [comment]
This command is the mediawiker's function, which makes request to wiki's API for rendering page in html.

**Comment by Kristinita** [comment]
@tosher, whether you in the future plan to make a plug-in so that it was possible to preview without resaving, reload of the page and reload page in the browser? For example, as writing text on Markdown by means of [OmniMarkupPreviewer](https://github.com/timonwong/OmniMarkupPreviewer)

![Markdown OMP](http://i.imgur.com/oLAAbvo.gif)

**Comment by reagle** [comment]
@tosher, I meant that I'd expect to see the command by hitting window+w  (mediawikir's commands) rather than ctrl+shift+p (sublime's palette). (Or it should at least / also be in mediawikir's commands.)

**Comment by tosher** [comment]
@reagle, hmm, this comman is available in ST's palette as **Mediawiker: Page preview** and in Mediawiker's palette as **Page preview** (last command, before snippets).
If you have redefined version in your user's config, please remove it, or move the string with this command from default config (if you need custom version of menu).

**Comment by tosher** [comment]
@Kristinita  - with the same effect - no. Wiki page generation - it's a real request to wiki api. I don't want to generate on-the-fly *ddosing* :) Markdown preview - local process, mediawiki - not.
But, i'll think on preview with one local file..

**Comment by reagle** [comment]
@tosher, that fixed it, thanks!
