### ISSUE TITLE
Scopes in infobox templates

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#65]
What scopes at elements on which shooters show?

![Scopes in infobox templates](http://i.imgur.com/tJe1hA3.jpg)

`|` , parameter, `=` and value.

I didn't find that these scopes were involved in your `.tmTheme` files. Thanks.

**Comment by tosher** [comment]
All scopes are defined in tmLanguage file (*MediawikiNG.tmLanguage*).
You can check it with <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>p</kbd> shortcut.

After that, color scheme defines how to colorize text with this scopes. If scope is not supported in color scheme - it will be shown by parent scope and so on.

From description to plugin:
**Note**: Not all color schemes fully supports syntax highlighting scopes required by markup languages like Mediawiki or Markdown. On this moment, color schemes with better support are: Twilight, Sunburst, Eiffel. Also, Mediawiker package includes Twilight (Mediawiki), Eiffel (Mediawiki) and Mediawiker_Dark/Mediawiker_Light schemes with improved highlighting for mediawiki syntax.

**Comment by Kristinita** [comment]
> You can check it with <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>p</kbd> shortcut.

How further I can copy the text from Status Bar?

**Comment by tosher** [comment]
Are you on ST2? In ST3 scopes are shown in popup message box.. will be better to move on ST3 instead of old Sublime 2nd version.

**Comment by Kristinita** [comment]
@tosher, I use Sublime Text 3, Build 3103. Scopes are shown in Status Bar:  

![Status Bar message](http://pokit.org/get/img/947f44360196769968cd6f9f3f4bd56e.jpg)

What can I make that scopes were shown in popup message box?

**Comment by tosher** [comment]
Ohh, maybe it's already implemented in Dev builds only.. (current - Build 3111)
You cant try to use some plugin for scopes, for example:
* https://packagecontrol.io/packages/ScopeHunter

**Comment by Kristinita** [comment]
@tosher, unfortunately, [this plugin doesn't work for me](https://github.com/facelessuser/ScopeHunter/issues/30). And [ScopeHunter online](https://tmtheme-editor.herokuapp.com) don't support wiki-markup.

**Comment by Kristinita** [comment]
Problem [is solved](http://ru.stackoverflow.com/a/516668/199934). Please, close issue.
