### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#66]
For quite some time now the mechanism of notifications is entered into Wikipedias.

![Notification 1](https://i.gyazo.com/54c83ffe1002c52c0cbe2973becf7068.png)
![Notification 2](https://i.gyazo.com/22e782f8f256219fd47ee6a62698da54.png)

May you realize so that users of Sublime Text could receive notices and when editing Wikipedia by means of Mediawiker? Thanks.

**Comment by tosher** [comment]
Please, check the new 3.0.9 version

**Comment by Kristinita** [comment]
@tosher, I see notifications in browser, but no in Sublime Text. When I press <kbd>Get Notifications</kbd>, occurs nothing.

![Notification](https://i.gyazo.com/8d3bbd166afd970334e953f7b06573cb.png)

Perhaps, there is a communication between [this](https://github.com/tosher/Mediawiker/issues/72) problem.

I would like to receive notices as follows. I open any article for editing → if notices are, they are displayed at me in Sublime Text, — if there are no notices somewhere, occurs nothing.

Thanks.

**Comment by tosher** [comment]
Can you generate some event which produce notification for [me](https://ru.wikipedia.org/w/index.php?title=Участник:Tshr)?

**Comment by Kristinita** [comment]
@tosher , [OK](https://ru.wikipedia.org/w/index.php?title=%D0%9E%D0%B1%D1%81%D1%83%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%B0:Tshr&oldid=78313097).

**Comment by tosher** [comment]
Thanks..
I know about this effect, maybe different versions of the extenstion generate different types of objects.
Will research..

**Comment by tosher** [comment]
Updated, please check the new version.

**Comment by Kristinita** [comment]
> Updated, please check the new version.

I apologize, the new Mediawiker version was loaded automatically?

I didn't see changes. Traceback after pressing <kbd>Get Notifications</kbd>

```
Traceback (most recent call last):
  File "D:\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "D:\Sublime Text 3\Data\Packages\Mediawiker\mediawiker.py", line 1474, in run
    for n in ns.keys():
AttributeError: 'list' object has no attribute 'keys'
```

And sometimes I still have [this problem](https://github.com/tosher/Mediawiker/issues/72#issue-154403387). Thanks.

**Comment by tosher** [comment]
I think it was not updated version. After update it must works fine - i'm pushed the new release marks.

**Comment by Kristinita** [comment]
@tosher, thanks, it's work!

You can make so that newest notifications were above, and oldest below? Now occurs on the contrary.

![Notifications](https://i.gyazo.com/bc8e985e7e185b241d55c19bc41ef49e.png)

**Comment by tosher** [comment]
Yes it's possible.

Hmm.. on your screen don't shown the *read* char on the right side of the message.. will check it..

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.1
