### ISSUE TITLE
Follow link?

### ISSUE THREAD

**Issue by reagle** [tosher/Mediawiker#67]
Is there a function and shortcut to follow a wiki link such that the target is opened in a new tab?

**Comment by tosher** [comment]
**Open inline** from context menu, not?

**Comment by reagle** [comment]
I had placed my cursor within a link (between `[[` and `]]`) and tried that but nothing happened. 
I had searched for a description of this function and [found](https://github.com/tosher/Mediawiker/releases): "Experimental Open inline command - context menu item for opening pages under cursor".
This sounded like what I thought should happen.
However, after playing around with it some more, it looks like this will open *any* text that is **selected**.
Is that correct?

**Comment by tosher** [comment]
Oh, yes, you are right!
Scribunto modules, templates with `{{...` substring, and selected links supported.

And you can:
* Select link text, than **Open page** command - the same effect as inline.
* **Show internal links** command, than select link from list..

**Comment by reagle** [comment]
Okay, I recommend including some documentation to this effect. Thanks for the clarification!
