### ISSUE TITLE
Open inline

### ISSUE THREAD

**Issue by TriMoon** [tosher/Mediawiker#68]
When used on a pagename with namespace it doesn't work.
Example select a text between the curly brackets like {{<code>:User:Yourusername/somepage</code>}}, this will NOT open the correct page.
In most cases it will return <code></code> in a page with tab-name <b>Template:{{:</b>

**Comment by tosher** [comment]
`{{` - is not using for page links, it's for templates or functions..
Internal links must be in square brackets: `[[page_name]]`.
After that, you can select `page_name` and click on **Open inline** from context menu.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/issues/67

**Comment by TriMoon** [comment]
I know the diff between <code>{{...}}</code> and <code>[[...]]</code> :)
The issue I'm reporting is about Template-usage in other namespaces as <code>Template:</code>, like the example i gave is in <code>User:</code>, the main-namespace is <code>:</code> and is used to call templates outside the <code>Template:</code> namespace.
This is standard MediaWiki behaviour...
So your code should allow this also because it is widely used... ;)

**Comment by tosher** [comment]
Please, check the new 3.0.9 version.

**Comment by TriMoon** [comment]
I'll try to report back on this, when i find time again to test that part.
/to be continued....

**Comment by tosher** [comment]
**Open inline** command was removed:
https://github.com/tosher/Mediawiker/releases/tag/3.1.7
