### ISSUE TITLE
Help: Unable to open pages on this wiki

### ISSUE THREAD

**Issue by TriMoon** [tosher/Mediawiker#69]
I'm not sure why im unable to open any page using this setup:
<pre>
"mediawiki_site":
	{
		"Project Gorgon":
		{
			"domain": ".projectgorgon.com",
			"host": "projectgorgon.com",
			"pagepath": "/wiki/",
			"password": "mypassword",
			"path": "/w/",
			"username": "myusername"
		}
	}
}
</pre>
I tried using "" as domain, and "/" as path and combinations but no luck..
I keep getting an error message telling me WrongPass.
I'm sure i use the correct username and password that i also use to login to the site.

**Comment by tosher** [comment]
http://projectgorgon.com/wiki/Special:Version
**Entry point URLs**

**Comment by TriMoon** [comment]
I know about those, but what settings do i need for it to work?

**Comment by tosher** [comment]
```
		"projectgorgon.com":
		{
			"domain": "",
			"host": "projectgorgon.com",
			"http_auth_login": "",
			"http_auth_password": "",
			"https": false,
			"pagepath": "/wiki/",
			"password": "your_password",
			"path": "/w/",
			"proxy_host": "",
			"use_http_auth": false,
			"username": "you_username"
		},

```

**Comment by TriMoon** [comment]
I added the missing fields from your json, but....
I'm still unable to open any page with or without username/password. :/
When i remove the username/password lines i get <code>Pagename was cleared.</code> at the status bar.
Any ideas why I'm unable while you seem to be able to open a page without username/password?

**Comment by tosher** [comment]
`Pagename was cleared` - always shown - it's just preparing page name for opening..

If you insert page:
`https://en.wikipedia.org/wiki/Capon_Lake_Whipple_Truss_Bridge`

it will open:
`Capon_Lake_Whipple_Truss_Bridge`

..and other small conversions.

Your new wiki site is active in configuration?

**Comment by TriMoon** [comment]
Well it's not my wiki site, but yes we can login and edit like any other wiki.
The only difference with other wikis as far as i noticed was the login that gets handled by their web page.
(They use same accounts for game, forum and wiki.)

I finally managed to load pages, it was only possible with empty values for password and login...
But being read-only aint of real use :tongue:

**Comment by tosher** [comment]
Maybe authorization type, used on this wiki is incompatible with standard mediawiki auth. process in the plugin :(

**Comment by danmichaelo** [comment]
Hm, yeah, it's using [AuthJoomla2](Extension:AuthJoomla2), so I guess you cannot login at http://projectgorgon.com/wiki/Special:Login either. Unless Jomla provides http auth (or oauth), I guess you're out of luck. And AuthJoomla2 doesn't seem to be open source anymore?

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/issues/83#issuecomment-233984172
Yep.

And latest version from 2013 year..
```
This extension's page is outdated. It was written for an older version of MediaWiki and may not apply to the most recent version.
```
