### ISSUE TITLE
Stylesheets in preview

### ISSUE THREAD

**Issue by TriMoon** [tosher/Mediawiker#70]
It uses the wrong prefix to construct the stylesheet url <code>/w/load.php</code> instead of <code>/load.php</code> see:

1. <code>&lt;link  rel="stylesheet" href="http://templates.wikia.com/w/load.php?debug=false&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=vector"/&gt;</code>
2. <code>&lt;link rel="stylesheet" href="http://templates.wikia.com/w/load.php?debug=false&amp;lang=ru&amp;modules=ext.geshi|ext.visualEditor.viewPageTarget.noscript|mediawiki.legacy.commonPrint,shared|mediawiki.sectionAnchor|mediawiki.skinning.interface|mediawiki.ui.button|skins.vector.styles&amp;only=styles&amp;skin=vector&amp;*" /&gt;</code>

These links give a 404 unless manually corrected via the developer tools inline functionality on the page.

My current settings for the wiki in question is:
<pre>"Wikia-Templates": {
	"domain": "",
	"host": "templates.wikia.com",
	"http_auth_login": "",
	"http_auth_password": "",
	"https": false,
	"pagepath": "/wiki/",
	"password": "MyPassword",
	"path": "/",
	"proxy_host": "",
	"use_http_auth": false,
	"username": "MyUsername"
}</pre>

Also the as can be seen in the 2nd stylesheet link the language seems to be hardcoded to <code>lang=ru</code>

**Comment by TriMoon** [comment]
Issue #64 seems related

**Comment by tosher** [comment]
Closed as duplicate
