### ISSUE TITLE
Changes are not saved in Russian Wikipedia

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#72]
I am doing edits in Russian Wikipedia, but cannot save (<kbd>Ctrl + S</kbd>) my changes. In other sites changes save [correct](https://traditio.wiki/w/index.php?title=%D0%A2%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D1%8F:%D0%9F%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0&diff=prev&oldid=574636), I see Status Bar message: `%PAGENAME% was succesfully published in wiki`,  but when I save the changes in the Russian Wikipedia, I also don't see anything in my Status Bar. Changes in the Russian Wikipedia ceased to be maintained after the last update of the Mediawiker.

Part of my <kbd>Settings - User</kbd> file:

```
"mediawiki_site":
	{
		"Русская Википедия":
		{
			"domain": "",
			"host": "ru.wikipedia.org",
			"pagepath": "/wiki/",
			"password": "MyPassword",
			"path": "/w/",
			"username": "AnimaAWB"
		},
```

Thanks.

**Comment by tosher** [comment]
Hmm, on my test, all works fine:
https://ru.wikipedia.org/w/index.php?title=Участник:Tshr&action=history

Maybe wrong password?

**Comment by Kristinita** [comment]
@tosher  no, in the browser I normally come into the account with the same password.

To the last update saving of pages in the Russian Wikipedia worked correctly.

**Comment by Kristinita** [comment]
@tosher  I two times rebooted Sublime Text 3, now edits is [saved](https://ru.wikipedia.org/w/index.php?title=%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%9F%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0&diff=prev&oldid=78312988). I'm sorry to trouble you.
