### ISSUE TITLE
Search Namespaces

### ISSUE THREAD

**Issue by dbeckmann** [tosher/Mediawiker#73]
Is it possible to extend the search function outside the main namespace?
Also, how do I open the pages returned by the search? They don't show up in the internal links list, since they are only enclosed by a single bracket (not double - I guess this is what the API returns) - and right-clicking on them doesn't work.

**Comment by tosher** [comment]
Search namespaces:
```json
"mediawiker_search_namespaces": "0, 500"
```

Open pages:
Just select text and hit **Open page** command (<kbd>Alt</kbd>+<kbd>F3</kbd>, by default)

**Comment by dbeckmann** [comment]
OK, I got it to work -
But, instead of "0, 500" - it needs "0|500" according to the MW API
documentation.
Thanks for pointing out the setting.
