### ISSUE TITLE
Right-click Open Inline: Doesn't open subpages

### ISSUE THREAD

**Issue by dbeckmann** [tosher/Mediawiker#74]
If I right-click on a properly double-bracketed link which happens to have a subpage (e.g. xxx/yyy), only the parent page is opened (e.g. xxx). The correct page opens with the menu command of "show internal links".

**Comment by tosher** [comment]
Will check this moment, must works as i think..

**Comment by tosher** [comment]
Please, check the new version, 3.1.0

**Comment by dbeckmann** [comment]
OK, I confirm it works.
Thanks.
