### ISSUE TITLE
Enable Segment (code) Folding

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#77]
I'm assuming this is a future of the Syntax Highlighting which enable you to classify "code block" and this way one can fold/hide code.

Currently this option is very required for long pages where I work both on the top segment and the bottom segment.

code blocks for
 - Headers `H#`/`==`
 - Tables (`{|`)
 - HTML tags, like `div`,`nowiki`
 - and multiline templates - `{{xxx| .... }}`

Thanks,

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.5

**Comment by rabin-io** [comment]
wow thanks, 

small "bug" is that you can't fold/unfold from the sidebar, which some times it easier to just scroll to the section and use the mouse, without moving the courser into the code block.

**Comment by tosher** [comment]
I know, but current sublime's api not support creation of the standard folding gutters :(

P.S. For folding with current gutters not needed to move cursor - just move mouse over the gutter (without click).

**Comment by rabin-io** [comment]
I'm probably doing it wrong, but i can't fold/unfold only by placing the mouse curser on the gutter.
I please my mouse curser over the gutter (e.g the first Header in the page), while my text caret is on the end of the page, pressing `ctrl+shift+[ or ctrl+shift+]` dose nothing for me. It's only when i place my caret in the text block, the above shurtcuts works.

**Comment by tosher** [comment]
Shortcuts works by cursor position only, only gutters (icons on the left side, before line numbers) works by mouse-over event.

**Comment by rabin-io** [comment]
I'm using ST3, but still not working for me with the mouse.

Never mind, the keyboard option is good enough for me.

Thanks.

**Comment by tosher** [comment]
If it not works, it must be fixed :)
Maybe some new details will help to fix the problem.

**Comment by tosher** [comment]
Bug, in current version:
```
== Features ==
The following is a list of features of Sublime Text:<ref>{{cite web |url=http://www.sublimetext.com/|title=Sublime Text |publisher=Sublime HQ Pty Ltd |accessdate=14 March 2014}}</ref>
```
Gutter folding heading, but not template, because nearest point not in template region. 
Will think..

Also, it not works correctly with templates in templates.. more things for **TODO**.

**Comment by rabin-io** [comment]
I really don't know what else to add, 

![screen capture](https://cloud.githubusercontent.com/assets/5116363/16931570/4938fb08-4d4a-11e6-8798-f84e1c44c1d3.gif)

**Comment by tosher** [comment]
Which ST3 version are you using?

**Comment by rabin-io** [comment]
Using ST3 Build 3114, and nothing in the console when I click the gutter.

**Comment by tosher** [comment]
I'm using 3118, dev channel..
Maybe some functions has differences, will try to check it.

**Comment by tosher** [comment]
Build 3116
* API: Added on_hover(view, point, hover_zone) event

This event is using for process gutters folding.

**Comment by rabin-io** [comment]
OK, tested with 3118, and it's working.
can't say i like the idea of fold-on-hover, can it be on click event ?

**Comment by tosher** [comment]
I don't like too :) ..and it can be switching off.
With current API - no. 
Waiting for updates..

**Comment by rabin-io** [comment]
So this is something which needs to be resolved by the ST dev team. As far as I'm concerned, this issue can be closed as it solved the original request.
