### ISSUE TITLE
Mediawiker 'tools' are disabled

### ISSUE THREAD

**Issue by olihawes** [tosher/Mediawiker#78]
I've installed Mediawiker by zip archive, and followed the setup instructions on the wiki. All of the options under Tools -> Mediawiker are disabled [like so](https://cloud.githubusercontent.com/assets/3943913/16121672/15476370-33dc-11e6-85b2-93fbff2f8dc9.png).

Have I missed a stage of setup?

Using Sublime Text 3 Build 3114 on Windows 10.

**Comment by tosher** [comment]
It's maybe error in the config file..
