### ISSUE TITLE
[Mediawiki NG] Bug in page «Кошка»

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#80]
Ruwiki, https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%88%D0%BA%D0%B0 . Bug, since the line 1508:

![Кошка баг](http://i.imgur.com/WzeA36u.png)

Thanks.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.7
