### ISSUE TITLE
[Mediawiki NG] Bug in page «Карл Линней»

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#81]
Cyclowiki, page `Карл Линней`, http://cyclowiki.org/wiki/%D0%9A%D0%B0%D1%80%D0%BB_%D0%9B%D0%B8%D0%BD%D0%BD%D0%B5%D0%B9 since the line 220:

![Карл Линней](http://i.imgur.com/1DNlaZO.png)

Thanks.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.7
