### ISSUE TITLE
[Mediawiki NG] Some notes

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#82]
All examples are followed from article of the Russian Wikipedia «Кошка» — https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%88%D0%BA%D0%B0 .
<br />

1. If in templates the symbol ` | ` costs at the beginning of a line, scopes are displayed correctly if at the beginning of a line there are spaces — incorrectly. 

```
{{cite web
| author      = 
 | date        = 
| url         = http://life.familyeducation.com/cats/hygiene/45696.html
 | title       = Keeping Up with Your Cat's Hygiene
 | work        = 
| publisher   = Family Education
 | accessdate  = 2010-06-25
 | archiveurl  = http://www.webcitation.org/67mD5bdZo
| archivedate = 2012-05-19
}}
```

![Templates](http://i.imgur.com/dA3gIeU.png)
<br />
2. There are no separate scopes for the `<blockqoute>` tag. Scopes same, as at contents between tags `<blockqoute></blockquote>`.

```
<blockquote>… while the '''feral and free-living domestic cat, Felis catus,''' can survive in the 
solitary state …, social groups that have internal structure, and in which group members recognize
each other and engage in a variety of social behaviors, are formed whenever there are sufficient 
food resources to support a group … '''In other words, they are a social species.'''</blockquote>
```
![Blockquote](http://i.imgur.com/IYkFFGc.png)
<br />
3. There are no separate scopes at brackets at the closing tag `</ref>`. Scopes at brackets same, as well as at the tag `ref`.

`Некоторые учёные считают, что кошка и вовсе не является одомашненным животным, а сама
могла прийти к человеку, так как в селениях всегда в достатке водились [[Синантропные организмы|синантропные животные]] или, проще говоря, многочисленные грызуны и птицы. Таким образом кошка нашла для себя удобный источник пищи, закрепившись на «новой нише». Сосуществование человека и кошки было взаимовыгодным, так как вторые избавлялись от популяции грызунов, часто становившихся источниками заболеваний и порчи хозяйства<ref name="animaux" /><ref name="vesti">http://www.vesti.ru/doc.html?id=1168465&cid=2161 Кошки сами решили жить рядом с человеком 5000 лет назад</ref>. Также весомым доводом противников идеи одомашнивания остаётся тот факт, что, по их мнению, кошка показывает интерес к человеку только до тех пор, пока ей это выгодно, то есть маленький хищник не способен на верность<ref name="animaux" />. Другие же учёные продвигают иную точку зрения. По их мнению, факт того, что кошки подвергались одомашниванию,`<br />
![Ref](http://i.imgur.com/yrjKWlI.png)
<br />
Thanks.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.7
