### ISSUE TITLE
readapidenied (You need read permission to use this module)

### ISSUE THREAD

**Issue by rabin-io** [tosher/Mediawiker#83]
After upgrading my wiki from 1.26.2 -> 1.27.0 (keeping the same configuration), 
Mediawiker can't open pages any more, and I get this error message in the console.

```
/home/USER/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/opt/sublime_text_3_build_3114/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mediawiker.py", line 227, in run
    page = mw.get_page(sitecon, title)
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mwutils.py", line 152, in get_page
    return site.Pages[title]
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mwclient/listing.py", line 182, in __getitem__
    return self.get(name, None)
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mwclient/listing.py", line 200, in get
    return self.page_class(self.site, name, info)
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mwclient/page.py", line 36, in __init__
    inprop='protection', *extra_props)
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 224, in api
    if self.handle_api_result(info, sleeper=sleeper):
  File "/home/USER/.config/sublime-text-3/Packages/Mediawiker/mwclient/client.py", line 247, in handle_api_result
    info['error']['info'], info['error']['*'])
Mediawiker.mwclient.errors.APIError: ('readapidenied', 'You need read permission to use this module', 'See https://wiki.office/api.php for API usage')
/home/USER/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Mediawiker exception: ('readapidenied', 'You need read permission to use this module', 'See https://wiki.office/api.php for API usage')
```

Enabling anonymous read to the wiki, restore the option to access the wiki via ST.

```
$wgGroupPermissions['*']['read'] = true;
```

**Comment by tosher** [comment]
You can't opening pages without authorization?

**Comment by rabin-io** [comment]
when the above setting is set to false  (`$wgGroupPermissions['*']['read'] = fasle;`) I get the above errors. The only thing (that i think off) that was changed is the Mediawiki version, which I upgraded from 1.26.2-> 1.27.0.

My ST setting for the plugging haven't changed.

**Comment by tosher** [comment]
As i know, in older versions of the Mediawiki core, `reading for all` was permitted by default.
Maybe in new version it's not default behavior.. and permission required now.

**Comment by rabin-io** [comment]
This is what i came be doing some googleing - https://www.mediawiki.org/wiki/API:FAQ#do_I_get_the_readapidenied_error.3F



> ### readapidenied error?
> The wiki you're querying contains private content and requires users to log in in order to be able to read all pages. **This means that a client needs to be logged in to query any information** at all through the API. See the quick start guide for more information. It's not currently possible to query the contents of whitelisted pages without logging in, even though they're available in the regular user interface.

Isn't that what the user/pass are for ? or maybe you need to keep some kind a cookie/token to work with the API in this mode ?

**Comment by TriMoon** [comment]
I bet #69 is related to this 😉

**Comment by tosher** [comment]
With amount of bet..? :)
In #69 wiki version: [1.22.2](http://projectgorgon.com/wiki/Special:Version)
