### ISSUE TITLE
Opening Pages Inconsistent / Opens untitled page every other Open Page

### ISSUE THREAD

**Issue by Pajellen** [tosher/Mediawiker#84]
Keep getting a consistent issue with opening a page with Mediawiker, every other attempt to open a page using either Alt+F3 or Command Palette will open an Untitled new file page. To replicate it:

- Hit Alt+F3 or open Command Palette and Type Mediawiker Open Page
- Type in a Page name (Example, Main Page)
- Repeat steps with same page name several times (Usually 2-3 times will make it happen)

One of the two attempts will only open an Untitled new file page, not open up the wiki page. Not a config issue since a page will come up on 1 of the 2 or so attempts, almost seems like the command to open page is getting mixed up with another command in Sublime Text after a few attempts. I have tried changing the Keymapping to the command as well, still no dice. Linked below is a GIF of the issue.

![mediawiker open page issue](https://cloud.githubusercontent.com/assets/12768295/16994390/c537b078-4e6c-11e6-8698-411eeba0e8a9.gif)

**Comment by Pajellen** [comment]
Looked a bit more into this, looks to be a function of the extension itself with the:

"mediawiker_newtab_ongetpage": true,

Looks like the issue is that the new tab page doesn't open automatically when sending the Open Page command, only on the second. If I set to false the issue doesn't happen anymore but I can't open additional pages without opening a new file and then using the Open Page option.

**Comment by tosher** [comment]
Thanks for report.
It's on ST3?

**Comment by Pajellen** [comment]
Yep, build 3114 Stable Channel. I also noticed I could replicate the issue above where after I Opened a Page successfully, if I opened the Open Page prompt again and just hit the ESC key the Untitled new file tab would pop up without me needing to type in anything. Seems to further confirm that the command for the newtab_ongetpage function is getting stuck.

**Comment by tosher** [comment]
Commit with fix will be in 10 minutes. It's not newtab problem.

**Comment by Pajellen** [comment]
Gotcha, will give an update as soon as the commit shows up on my end.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.6

**Comment by Pajellen** [comment]
Just updated to 3.1.6, issues resolved with default settings. Closing Issue, thanks!
