### ISSUE TITLE
Syntax file could not be loaded

### ISSUE THREAD

**Issue by Silberling** [tosher/Mediawiker#85]
![capture2](https://cloud.githubusercontent.com/assets/4000178/17176371/afcd0abc-540c-11e6-8d5f-e3df21d04921.PNG)

> error: Error loading syntax file "Packages/Mediawiker/MediawikiNG.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

MediaWiker 3.1.8 on Windows Sublime 64bit rev 3119

**Comment by tosher** [comment]
It's with a this is a particular page/text or not?
And which version of Sublime Text used?

**Comment by Silberling** [comment]
I tried several different Pages all with the same error. This error occurs once after sublime got started and i opened the first page. After that, the syntax doesn't get loaded so the error does not appear. After restarting sublime the error comes up again, once again.

I'd like to mention this is a private wiki, a dev notebook. I have this issue for some days. I don't know if this is since the 3119 update or if there was a plugin update which could have caused this.

Manually switching to Mediawiki syntax leads to the same error. Switching to Mediawiki NG manually, too.

Does the "Mediawiki" syntax without the NG belong to Mediawiker? Could this be a problem of Sublime?

**Comment by tosher** [comment]
https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/24

**Comment by Silberling** [comment]
Did search, didn't find. Thanks for the link ;-)

**Comment by tosher** [comment]
Did it help with problem?

**Comment by Silberling** [comment]
It did
