### ISSUE TITLE
Support OAuth

### ISSUE THREAD

**Issue by danmichaelo** [tosher/Mediawiker#88]
Hi, OAuth support was added in https://github.com/mwclient/mwclient/commit/b4640d3b2537cfd6d17e2034ee53480b5ed2d4fe , probably a good idea to pull this into Mediawiker too.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.8.final

**Comment by Kristinita** [comment]
@tosher , may you add manual, how Mediawiker users can authorise in wiki-site use OAuth? Thanks.

**Comment by tosher** [comment]
https://www.mediawiki.org/wiki/Extension:OAuth#Register_your_Consumer
