### ISSUE TITLE
Semicolons in lists syntax bug

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#90]
For example, page «Поиск Кристиниты» in Cyclowiki <http://cyclowiki.org/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:%D0%A1%D0%B0%D1%88%D0%B0_%D0%A7%D0%B5%D1%80%D0%BD%D1%8B%D1%85/%D0%9F%D0%BE%D0%B8%D1%81%D0%BA_%D0%9A%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%BD%D0%B8%D1%82%D1%8B>, line 383.

```
## авторы признаются, что являются любителями,
## авторы контента подписаны именами и фамилиями, а быстрым гуглением не получается определить, профессионалы ли они в теме;<br /> то в случайном порядке отбирается несколько статей ресурса. Возможны 3 варианта:
### на с. указываются использованные материалы,
```

![Semicolons](http://i.imgur.com/sVFV8tE.png)

After semicolons scope of all list elements is `text.html.mediawiki markup.list.mediawiki `. All list syntax highlight one color of scope `text.html.mediawiki markup.list.mediawiki` (pink for me). 

If I remove the semicolons in list, syntax highlighted correctly.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.11
