### ISSUE TITLE
Preview as LiveReload

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#91]
Now to see the changes made, I have to press <kbd>Alt+F3</kbd>, then Page Preview, and the page opens in the browser. To view the next change, I again have to do the same. It takes a lot of time and in the browser open many tabs.

I suggest that, as in LiveReload. After I click, for example, <kbd>Ctrl+S</kbd>, and the page is refreshed in the browser. It is more user-friendly than it is now, and there is no DDOS wiki-site.

[![LiveReload](http://i.imgur.com/ZbVnYcZ.png)](https://youtu.be/sUY06rWklXU?t=72)

Thanks.

**Comment by tosher** [comment]
If in the settings we have a full file name as preview file:
```
"mediawiki_preview_file": "Wiki_page_preview.html"
```
Preview will be generated in permanent file and we can just to reload the page in the browser after preview generation (or you can use live reload).

**Comment by Kristinita** [comment]
I'm sorry, can I do so that I a run `mediawiker_preview` command and I could see a change in my browser? Now I have to press the additional time <kbd>Ctrl+S</kbd>, to see the changes in my browser.

See similar problem: <https://github.com/alexnj/SublimeOnSaveBuild/issues/38#issue-174913131>.

**Comment by Kristinita** [comment]
As in [this](https://github.com/alexnj/SublimeOnSaveBuild/issues/38#issuecomment-244600401) answer not working for me.

My settings:

```
    {
	    "keys": ["alt+context_menu"], "command": "run_multiple_commands", "context": [{ "key": "selector", "operand": "text.html.mediawiki" }],
	    "args": {
	        "commands": [{
	            "command": "mediawiker_preview",
	        },{
	            "command": "mediawiker_preview",
	            "delay": 1000
	        },
	    ]
	    }
	 },
```

In console:
```

key evt: alt+context_menu
command: run_multiple_commands {"commands": [{"command": "mediawiker_preview"}, {"command": "mediawiker_preview", "delay": 1000}]}
{'command': 'mediawiker_preview'}
{'command': 'mediawiker_preview', 'delay': 0}

```

**Comment by tosher** [comment]
Why needs to run `mediawiker_preview` command twice?

**Comment by Kristinita** [comment]
> Why needs to run mediawiker_preview command twice?

I no needs, its no work for me 😺 .

In [#38](https://github.com/alexnj/SublimeOnSaveBuild/issues/38#issuecomment-244600401) I need run command 2 times, because I don't see changes in browser if I run command one time. 

In LiveReload I can enable plugin `Simple Reload with delay ` — wait 400 ms than refresh page, when file is saved, and I no needs save file 2 times.

Thanks.

**Comment by tosher** [comment]
New preview scenario in 3.3.0, please, try it:
https://github.com/tosher/Mediawiker/releases/tag/3.3.0

**Comment by Kristinita** [comment]
@tosher, thanks, its worked for me! But:

+ If I run `Page Preview`, new tab open in my browser each time. What I need, that only one tab reload for me, not open many tabs?
+ Where I need to set `Autoreload` option?
+ What is «Nth change»?

Thanks.

**Comment by tosher** [comment]
Run **Configurator** command, select **Tab options** and set `autoreload` value.
* Nth - if `autoreload` value was set to 7 (N = 7 :) ), regeneration will run after every 7 changes.

**Comment by Kristinita** [comment]
@tosher , I think, that periodically preview after N changes is a not good idea.

1. Usually I need to make many changes or I need to debug my page, use several changes. Which value I need to make for `autoreload` option? If I make a big value, I don't want to preview my small changes; if I make a small value, many tabs in a browser will take my time.

I don't know, after a number of revisions I need a preview. This number is always different.

2. Many tabs open for me. It would be nice, if new tabs not will be created, but one tab will be refresh.

---

I think, that refresh tab in browser after run command by trigger — is a good idea.

Thanks.

**Comment by tosher** [comment]
If you want to view changes "right now", just run preview command - with autoreload > 0, it will run silence page update.

**Comment by Kristinita** [comment]
But new tabs will be open for me, not one tab refresh.

Thanks.

**Comment by tosher** [comment]
If Autorefresh is not zero - not, just regenerate preview html file.

**Comment by Kristinita** [comment]
Where I can set Autorefresh? I don't find this setting.

Thanks.

**Comment by tosher** [comment]
Ups, it's typo - `Autoreload`
