### ISSUE TITLE
No highlight text in <nowiki> tag

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#92]
For example, I have code:

`<nowiki>{{Биофото|Hypne2pg.jpg|ш=550|left|{{color|#ffa812|'''''Кликните по [http://i.imgur.com/C55SxAf.gif ссылке], чтобы увидеть анимацию.'''''}}|color=Crimson}}</nowiki>`

Code not highlight, scope for all elements between `<nowiki></nowiki>` tags is `text.html.mediawiki`.

![Nowiki](http://i.imgur.com/5QX3gDR.png)

I think it is possible to allocate nowiki tag is not such a color as the rest of the tag, or to highlight the content between the tags `<nowiki></ nowiki>`, not remove syntax highlight that without `<nowiki>`. But as it is now, in my opinion, it is not very good.

Thanks.

**Comment by tosher** [comment]
The scope between `nowiki` tag is: `text.html.mediawiki meta.tag.source.validhtml.mediawiki`.
It's highlighted as grayed block in Mediawiker_Dark theme, for example. 
Contents should not be highlighted, as the engine is not process this block.

**Comment by Kristinita** [comment]
Hmm, now it's work for me.
