### ISSUE TITLE
[Bug] Space after sfn template

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#93]
Page `Гипнэротомахия Полифила` of Russian Wikipedia, line 62.

_Without space before template_ bad:
![Without space](http://i.imgur.com/5AlMdNm.png)

_With space before template_ good:
![With space](http://i.imgur.com/r6nbEbv.png)

On this page several times broken lights, when before the template sfn no space.

Thanks.

**Comment by tosher** [comment]
https://github.com/tosher/Mediawiker/releases/tag/3.1.12
