### ISSUE TITLE
[Bug] Tag span in templates

### ISSUE THREAD

**Issue by Kristinita** [tosher/Mediawiker#96]
### Summary

Bug if `<span>` tag is in template.

### Expected behavior

![Expected span](http://i.imgur.com/XEP4SWO.png)

### Actual behavior

![Actual span](http://i.imgur.com/a8gPFVo.png)

### Steps to reproduce

I open page <http://cyclowiki.org/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:%D0%A1%D0%B0%D1%88%D0%B0_%D0%A7%D0%B5%D1%80%D0%BD%D1%8B%D1%85/%D0%9F%D0%BE%D0%B8%D1%81%D0%BA_%D0%9A%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%BD%D0%B8%D1%82%D1%8B>, line 222. After line 222 syntax highlights is bad for me.
If I delete `<span style="color:#ffa812">`, syntax highlights is normally for me.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by tosher** [comment]
With more correct positions of tags it works fine:
```mediawiki
{{Биофото
|Нестабильная поисковая выдача при добавлении XML-страницы .gif
|ш=550
|align=left
|текст='''''<span style="color:#ffa812">Кликните по </span>[http://data.cyclowiki.org/images/0/04/Нестабильная_поисковая_выдача_при_добавлении_XML-страницы_.gif <span style="color:yellow">ссылке</span>]<span style="color:#ffa812">, чтобы увидеть анимацию.</span>'''''
|color=Crimson
}}
```
But, i will check why it not works without..

**Comment by tosher** [comment]
I don't know how to make the intersections to work correct. I think will be better to write markup in correct order:
```
<tag><tag2></tag2></tag>
```
instead of 
```
<tag><tag2></tag></tag2>
```
or something..

We have a support of includes in syntax, but not intersections.
